docs: fix some urls
zitadel/zitadel pull request #3709
Opened 2022-05-25 09:14 UTC by eliobischof

- token endpoint is /oauth/v2/oauth/token
- zitadel.dev is internal only

2022-05-25 12:09 UTC, hifabienne commented on docs/docs/quickstarts/login/nextjs.md
> +    profileUrl: "https://api.zitadel.ch/oauth/v2/userinfo",
this urls are all wrong in my opinion. should be with {your_domain}

2022-06-01 13:17 UTC, mffap commented
@eliobischof could you have a look at the deploy logs? There are many broken links flagged. This PR seems related.

2022-06-30 11:45 UTC, livio-a requested changes
token endpoint has been fixed and is now /oauth/v2/token again

2022-07-14 09:35 UTC, mffap commented
@livio-a @eliobischof do we have an issue right now with different endpoints? or is the current version of the docs (without) this PR correct? This PR is confusing in that regard.

2022-07-14 12:35 UTC, eliobischof commented
Token endpoint changes are obsolete and for ZITADEL domains, we need a better solution than this PRs.
Closing.

2022-07-14 12:35 UTC, closed without merging