feat(console): deactivate, reactivate org
zitadel/zitadel pull request #3834
Opened 2022-06-16 12:06 UTC by peintnermax

2022-07-07 06:25 UTC, livio-a requested changes
can you please merge in alpha-v2 and provide a french translation for the de-/reactivate texts

2022-07-07 06:25 UTC, livio-a commented on console/src/assets/i18n/de.json
> +        "DESCRIPTION": "Sie sind im Begriff Ihre organisation zu reaktivieren. User können Sich dann wieder anmelden? Wollen Sie fortfahren?"
```suggestion
        "DESCRIPTION": "Sie sind im Begriff Ihre Organisation zu deaktivieren. User können Sich danach nicht mehr anmelden? Wollen Sie fortfahren?"
      },
      "REACTIVATE": {
        "TITLE": "Organisation reaktivieren",
        "DESCRIPTION": "Sie sind im Begriff Ihre Organisation zu reaktivieren. User können Sich danach wieder anmelden? Wollen Sie fortfahren?"
```

2022-07-07 11:27 UTC, peintnermax commented
added missing french translation 👍

2022-07-08 06:56 UTC, livio-a approved these changes

2022-07-08 06:58 UTC, merged