docs(guides): user metadata
zitadel/zitadel pull request #3838
Opened 2022-06-19 10:11 UTC by mffap

Adds a guide how to manually request user medata as reserved scope from ZITADEL.

Depends on zitadel-tools

2022-06-21 09:14 UTC, eliobischof requested changes

2022-06-21 09:14 UTC, eliobischof commented on docs/docs/guides/customization/user-metadata.md
> +
```suggestion
```

2022-06-21 09:14 UTC, eliobischof commented on docs/docs/guides/customization/user-metadata.md
> +<TabItem value="python" label="Python" default>
```suggestion
<TabItem value="python" label="Python">
```

2022-06-21 09:14 UTC, eliobischof commented on docs/docs/guides/customization/user-metadata.md
> +
only for the go tab

2022-06-23 08:32 UTC, eliobischof commented on docs/docs/guides/customization/user-metadata.md
> +Grab zitadel-tools to create the [required string](https://docs.zitadel.com/docs/apis/openidoauth/authn-methods#client-secret-basic) for Basic authentication:
```suggestion
```

2022-06-27 19:53 UTC, fforootd commented
@eliobischof can you conclude the review here please. TY

2022-06-28 10:24 UTC, eliobischof approved these changes

2022-06-28 17:34 UTC, merged