docs: fix tls description and limitations
zitadel/zitadel pull request #3884
Opened 2022-07-01 10:02 UTC by thesephirot

fixes tls descriptino for knative and adds a general disclaimer about limitations

2022-07-01 14:04 UTC, eliobischof commented on docs/docs/guides/installation/run/knative.mdx
>  or use the knative service yaml
also add the whats next section
![image](https://user-images.githubusercontent.com/12727842/176909928-2e132492-a895-4d08-b239-22907237cd16.png)

2022-07-01 14:10 UTC, eliobischof requested changes

2022-07-01 14:10 UTC, eliobischof commented on docs/docs/guides/installation/run/knative.mdx
> +--arg "admin" --arg "start-from-init" --arg "--masterkey" --arg "MasterkeyNeedsToHave32Characters"
does it work without the --tlsMode disabled flag?

2022-07-04 09:44 UTC, thesephirot commented on docs/docs/guides/installation/run/knative.mdx
> +- use an API gateway with valid certificates in front of the service
nope, loadbalancing is heavily dependend on the clients setup

2022-07-04 10:45 UTC, thesephirot commented
#notetomyself
cockroach db mem limits to 1GB

2022-07-04 12:16 UTC, thesephirot commented on docs/docs/guides/installation/run/knative.mdx
> +--arg "admin" --arg "start-from-init" --arg "--masterkey" --arg "MasterkeyNeedsToHave32Characters"
yes it does work without the flag

2022-07-05 10:37 UTC, thesephirot commented on docs/docs/guides/installation/run/knative.mdx
> +- configure an appropriate email server
done

2022-07-05 10:38 UTC, thesephirot commented on docs/docs/guides/installation/run/knative.mdx
> +--arg "admin" --arg "start-from-init" --arg "--masterkey" --arg "MasterkeyNeedsToHave32Characters"
removed admin

2022-07-07 11:25 UTC, thesephirot commented on docs/docs/guides/installation/run/knative.mdx
> +- use an API gateway with valid certificates in front of the service
makes sense. I`ve added a link

2022-07-07 11:33 UTC, merged