fix(console): apply labelpolicy if icon is provided, signout page
zitadel/zitadel pull request #4499
Opened 2022-10-05 13:29 UTC by peintnermax

2022-10-07 06:26 UTC, livio-a requested changes
can we check if there's a better solution... putting the whole policy json into the state param does not make sense to me

and it's not even an url safe value
![image](https://user-images.githubusercontent.com/9405495/194480823-a7a48396-6162-43bc-ae7e-3908d384b526.png)

2022-10-08 07:48 UTC, peintnermax commented
moved the policy to the localstorage now. write on signout and read and clear directly after it..

2022-10-11 06:43 UTC, hifabienne approved these changes

2022-10-17 12:09 UTC, livio-a approved these changes

2022-10-17 12:09 UTC, merged