fix: remove userid unique constraint and fix user list query
zitadel/zitadel pull request #4632
Opened 2022-10-28 05:21 UTC by livio-a

2022-11-01 16:15 UTC, adlerhurst requested changes

2022-11-02 12:56 UTC, livio-a commented on internal/query/user.go
> +			UserInstanceIDCol.identifier(): instanceID,
would it help if we set this where part in the prepare itself?

2022-11-03 14:01 UTC, adlerhurst commented on internal/query/user.go
> +			UserInstanceIDCol.identifier(): instanceID,
I would give that a try

2022-11-04 08:09 UTC, livio-a commented on internal/query/user.go
> +			UserInstanceIDCol.identifier(): instanceID,
hmm or why don't we just add the instance_id to the join statements in the prepare (like we do with other left joins), so we don't need to pass the id to the prepare?
IMO this should result in the same performance, but i'll compare with explain analyze

2022-11-07 07:54 UTC, livio-a commented on internal/query/user.go
> +			UserInstanceIDCol.identifier(): instanceID,
fixed

2022-11-07 09:14 UTC, adlerhurst approved these changes

2022-11-07 09:33 UTC, merged