docs: azure ad actions and no mfa prompt
zitadel/zitadel pull request #4655
Opened 2022-11-04 11:21 UTC by hifabienne

2022-11-04 16:08 UTC, mffap commented on docs/docs/apis/actions.md
> +- [Actions Marketplace: Find example actions to use in your ZITADEL instance](https://github.com/zitadel/actions)
```suggestion
- [Actions Marketplace: Find example actions to use in ZITADEL](https://github.com/zitadel/actions)
```

2022-11-04 16:09 UTC, mffap commented on docs/docs/concepts/features/actions.md
> +- [Actions Marketplace: Find example actions to use in your ZITADEL instance](https://github.com/zitadel/actions)
```suggestion
- [Actions Marketplace: Find example actions to use in ZITADEL](https://github.com/zitadel/actions)
```

2022-11-04 16:10 UTC, mffap commented on docs/docs/guides/integrate/azuread-oidc.md
> +To not get this prompt if you are using the Azure AD you have to disable it.
```suggestion
If you don't want your users to get this prompt when using Azure, you have to disable this feature.
```

2022-11-04 16:11 UTC, mffap commented on docs/docs/guides/integrate/azuread-oidc.md
> +1. Go to the login behaviour settings of your instance or organization (depending on if you like to disable it for all or just this organization)
```suggestion
1. Go to the login behaviour settings of your instance or organization, depending if you like to disable it for all or just a specific organization respectively
```

2022-11-04 16:12 UTC, mffap commented on docs/docs/guides/integrate/azuread-oidc.md
> +Azure AD does not send the email verified claim in its token.
```suggestion
Azure AD does not send the "email verified claim" in its token.
```

2022-11-04 16:14 UTC, mffap commented on docs/docs/guides/integrate/azuread-oidc.md
> +To create the user with a verified email address you can add an action.
```suggestion
To create the user with a verified email address you must add an action.
```

2022-11-07 06:44 UTC, livio-a requested changes
the action will fail... the name of the action currently has to match one of the function names in the action itself

2022-11-07 08:24 UTC, mffap requested changes

2022-11-07 08:24 UTC, mffap commented on docs/docs/guides/integrate/azuread-oidc.md
> +2. Create a new action with the email verify script
```suggestion
2. Create a new action with the following code to set the email to verified automatically
```

2022-11-07 08:24 UTC, mffap commented on docs/docs/guides/integrate/azuread-oidc.md
> +To test the setup use a incognito mode and browse to your login page.
```suggestion
To test the setup use incognito mode and browse to your login page.
```

2022-11-07 14:34 UTC, hifabienne commented
> the action will fail... the name of the action currently has to match one of the function names in the action itself

I have changed it

2022-11-08 12:30 UTC, mffap commented
@hifabienne is this ready? if so, can you re-request a review, so we can get this docs merged, please?

2022-11-08 12:44 UTC, hifabienne commented
> @hifabienne is this ready? if so, can you re-request a review, so we can get this docs merged, please?

Yes from my perspective it is. I thought you are not finished with the review sue to the wip review comment.

2022-11-08 13:42 UTC, adlerhurst approved these changes

2022-11-09 08:48 UTC, livio-a approved these changes

2022-11-09 08:49 UTC, merged