docs: setup with service account docs
zitadel/zitadel pull request #4877
Opened 2022-12-14 10:02 UTC by stebenz

2022-12-15 17:07 UTC, mffap commented
@eliobischof @hifabienne can you pls provide me with an ETA when this PR will be reviewed?

2022-12-15 17:22 UTC, eliobischof commented
> @eliobischof @hifabienne can you pls provide me with an ETA when this PR will be reviewed?

I'll review soon, after dinner 🙂

2022-12-15 17:44 UTC, mffap commented
> > @eliobischof @hifabienne can you pls provide me with an ETA when this PR will be reviewed?
> 
> I'll review soon, after dinner 🙂

😀 Ok, not *that* urgent. Thanks!

2022-12-15 17:55 UTC, eliobischof commented
To me, it feels very odd to duplicate all platform installation instructions like this. I think, we should keep them as simple and maintainable as possible.

I'd rather just describe what options a user has and how key generation works in a separate page beneath self-hosted.  This page would then also be linkable from the terraform page, for example.

2022-12-15 17:57 UTC, eliobischof requested changes
https://github.com/zitadel/zitadel/pull/4877#issuecomment-1353490466

2022-12-16 10:07 UTC, eliobischof requested changes

2022-12-16 10:07 UTC, eliobischof commented on docs/docs/guides/deploy/kubernetes.mdx
> +#### Install an insecure zitadel release that works with localhost with a service account
can you move the DefaultUser component above this line, please?

2022-12-16 10:55 UTC, eliobischof submitted a review, later dismissed
Created a follow-up issue in order to resolve the disaggreement #4892

2022-12-16 13:09 UTC, eliobischof approved these changes

2022-12-16 13:09 UTC, merged