docs(self-hosting): add env vars for proxy configuration
zitadel/zitadel pull request #4916
Opened 2022-12-21 16:35 UTC by adlerhurst

2022-12-21 16:36 UTC, adlerhurst commented
@livio-a @eliobischof should we add the `NO_PROXY` env var as well? description can be found here: https://pkg.go.dev/golang.org/x/net/http/httpproxy

2022-12-21 17:09 UTC, eliobischof commented
> @livio-a @eliobischof should we add the `NO_PROXY` env var as well? description can be found here: https://pkg.go.dev/golang.org/x/net/http/httpproxy

Yes :-)

2022-12-21 17:13 UTC, eliobischof requested changes
> @livio-a @eliobischof should we add the `NO_PROXY` env var as well? description can be found here: https://pkg.go.dev/golang.org/x/net/http/httpproxy

Yes, and maybe directly link these specs?

2022-12-22 12:08 UTC, livio-a approved these changes

2022-12-22 12:42 UTC, eliobischof approved these changes

2022-12-22 12:42 UTC, merged