Production checklist
zitadel/zitadel pull request #4964
Opened 2023-01-02 11:03 UTC by thesephirot

I doublechecked some OS production checklists and I think a generic short list is IMO better suited as the individual setups may/will vary quite heavily.

@fforootd 
@eliobischof 

Did I miss something?

2023-01-02 11:09 UTC, fforootd commented
You are aware that we have https://zitadel.com/docs/self-hosting/manage/production , right?

It looks to me that we should integrate the content into that page.

Besides that, can you please use a semrel title and set this PR to "ready for review", ty!

2023-01-02 14:07 UTC, fforootd reviewed
More to come as soon as i have time again, but that and my comment [here ](https://github.com/zitadel/zitadel/pull/4964#issuecomment-1368851023) is what i can provide so far

2023-01-02 14:14 UTC, thesephirot commented on docs/docs/self-hosting/manage/production.md
> +- [] reduce the manual interaction with your platform to an absolute minimum
thats what I did, I find it ugly as well, I will doublecheck formatting anyways

2023-01-02 14:19 UTC, fforootd commented on docs/docs/self-hosting/manage/production.md
> +- [] reduce the manual interaction with your platform to an absolute minimum
In MD only with spaces should work if i remember correctly

See this test below:

- [ ] Test
- [] Test

2023-01-02 14:53 UTC, thesephirot commented on docs/docs/self-hosting/manage/production.md
> +- [] reduce the manual interaction with your platform to an absolute minimum
a space on the correct place, quite makes a difference, my bad. looks better now.

2023-01-03 12:59 UTC, thesephirot commented
> 

as for the redundancy, I am with you but don't want to rip the list into pieces. I will try to consolidate or put the list separately

2023-01-05 11:17 UTC, thesephirot commented
> ~You are aware that we have https://zitadel.com/docs/self-hosting/manage/production , right?~ ~It looks to me that we should integrate the content into that page.~
> 
> My preview was broken and did not show the same file... mybad 😁
> 
> Some thoughts/observations of mine for this:
> 
> * I we want to have one document we should rename the title. It make a little sense to me having a production checklist with a checklist in it.
> * Checklist boxes look broken in the preview https://deploy-preview-4964--docs-zitadel-com.netlify.app/docs/self-hosting/manage/production#checklist
> * Some of the content feels redundant since it is in text and checkboxes, I am not sure how we can reduce this
> * Besides that, can you please use a semrel title and set this PR to "ready for review", ty!

I had a play around. To me the best solution is to completely separate the checklist from the Production setup page. Sure there is some redundancy, but that is okay im my opinion as some steps might need further explanation on the "setup page".

2023-01-17 11:27 UTC, eliobischof requested changes

2023-01-17 11:27 UTC, eliobischof commented on docs/docs/self-hosting/manage/productionchecklist.md
> +  - [ ] secure the access by [ratelimits](https://zitadel.com/docs/apis/ratelimits) for specific endpoints (e.g. API vs frontend) to secure availability on high load
```suggestion
  - [ ] secure the access by rate limits for specific endpoints (e.g. API vs frontend) to secure availability on high load. See the [ZITADEL Cloud rate limits](https://zitadel.com/docs/apis/ratelimits) for reference.
```

2023-01-17 11:27 UTC, eliobischof commented on docs/docs/self-hosting/manage/productionchecklist.md
> +  - [ ] doublecheck your Firewall for IPv6 connectivity and change accordingly
```suggestion
  - [ ] doublecheck your firewall for IPv6 connectivity and change accordingly
```

2023-01-17 11:27 UTC, eliobischof commented on docs/docs/self-hosting/manage/productionchecklist.md
> +### infrastructure configuration
```suggestion
### Infrastructure Configuration
```

2023-01-17 11:27 UTC, eliobischof commented on docs/docs/self-hosting/manage/productionchecklist.md
> +  - [ ] separate `zitadel init` and `zitadel setup` for fast startup times when scaling ZITADEL
Add link to the updating and scaling page

2023-01-17 11:27 UTC, eliobischof commented on docs/docs/self-hosting/manage/productionchecklist.md
> +
- declare and apply zitadel configuration using the zitadel terraform provider (link)

2023-01-17 11:27 UTC, eliobischof commented on docs/docs/self-hosting/manage/productionchecklist.md
> +- [ ] Add [Custom Branding](https://zitadel.com/docs/guides/manage/customize/branding) if required
```suggestion
- [ ] add [custom branding](https://zitadel.com/docs/guides/manage/customize/branding) if required
```

2023-01-17 11:27 UTC, eliobischof commented on docs/docs/self-hosting/manage/productionchecklist.md
> +- [ ] configure a valid [SMTP Server](https://zitadel.com/docs/guides/manage/console/instance-settings#smtp) and test emails
```suggestion
- [ ] configure a valid [SMTP server](https://zitadel.com/docs/guides/manage/console/instance-settings#smtp) and test emails
```

2023-01-17 11:27 UTC, eliobischof commented on docs/docs/self-hosting/manage/production.md
> +We created a [Production Checklist](./productionchecklist.md) as a technical step by step guide.
```suggestion
We created a [production checklist](./productionchecklist.md) as a technical step by step guide.
```

2023-01-17 11:27 UTC, eliobischof commented on docs/docs/self-hosting/manage/productionchecklist.md
> +- [ ] High Availability for ZITADEL containers
```suggestion
- [ ] high availability for ZITADEL containers
```

2023-01-17 11:27 UTC, eliobischof commented on docs/docs/self-hosting/manage/productionchecklist.md
> +- [ ] High Availability for database
```suggestion
- [ ] high availability for database 
```

2023-01-17 11:27 UTC, eliobischof commented on docs/docs/self-hosting/manage/productionchecklist.md
> +  - [ ] follow the [Production Checklist](https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html) for CockroachDB if you selfhost the database or use [CockroachDB cloud](https
```suggestion
  - [ ] follow the [production checklist](https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html) for CockroachDB if you selfhost the database or use [CockroachDB Cloud](https://www.cockroachlabs.com/docs/cockroachcloud/create-an-account.html)
```

2023-01-17 11:27 UTC, eliobischof commented on docs/docs/self-hosting/manage/productionchecklist.md
> +  - [ ] configure backups on a regular basis for the Database
```suggestion
  - [ ] configure backups on a regular basis for the database
```

2023-01-17 11:27 UTC, eliobischof commented on docs/docs/self-hosting/manage/productionchecklist.md
> +- [ ] High Availability for critical infrastructure components (depending on your setup)
```suggestion
- [ ] high availability for critical infrastructure components (depending on your setup)
```

2023-01-17 11:27 UTC, eliobischof commented on docs/docs/self-hosting/manage/productionchecklist.md
> +  - [ ] Loadbalancer
```suggestion
  - [ ] loadbalancer
```

2023-01-17 11:27 UTC, eliobischof commented on docs/docs/self-hosting/manage/productionchecklist.md
> +  - [ ] [Reverse Proxies](https://zitadel.com/docs/self-hosting/manage/reverseproxy/reverse_proxy)
```suggestion
  - [ ] [reverse proxies](https://zitadel.com/docs/self-hosting/manage/reverseproxy/reverse_proxy)
```

2023-01-17 11:27 UTC, eliobischof commented on docs/docs/self-hosting/manage/productionchecklist.md
> +  - [ ] Web Application Firewall
```suggestion
  - [ ] web application firewall
```

2023-01-17 11:27 UTC, eliobischof commented on docs/docs/self-hosting/manage/productionchecklist.md
> +- [ ] Use a Layer 7 Web Application Firewall to secure ZITADEL that supports **[HTTP/2](/docs/self-hosting/manage/http2)**
```suggestion
- [ ] use a layer 7 web application firewall to secure ZITADEL that supports **[HTTP/2](/docs/self-hosting/manage/http2)**
```

2023-01-17 11:27 UTC, eliobischof commented on docs/docs/self-hosting/manage/productionchecklist.md
> +- [ ] configure a valid [SMS Service](https://zitadel.com/docs/guides/manage/console/instance-settings#sms) such as Twilio if needed
```suggestion
- [ ] configure a valid [SMS service](https://zitadel.com/docs/guides/manage/console/instance-settings#sms) such as Twilio if needed
```

2023-01-17 11:27 UTC, eliobischof commented on docs/docs/self-hosting/manage/productionchecklist.md
> +- [ ] configure your privacy policy, terms of service and a help Link if needed
```suggestion
- [ ] configure your privacy policy, terms of service and a help link if needed
```

2023-01-17 11:27 UTC, eliobischof commented on docs/docs/self-hosting/manage/productionchecklist.md
> +- [ ] make use of different Serviceaccounts to secure ZITADEL within your Hyperscaler or Kubernetes
```suggestion
- [ ] make use of different service accounts to secure ZITADEL within your hyperscaler or Kubernetes 
```

2023-01-17 11:27 UTC, eliobischof commented on docs/docs/self-hosting/manage/productionchecklist.md
> +- [ ] make use of a CDN Service if needed to ease maintainability and Firewall/DNS/WAF configuration
```suggestion
- [ ] make use of a CDN service if needed to ease maintainability and firewall/DNS/WAF configuration
```

2023-01-17 11:27 UTC, eliobischof commented on docs/docs/self-hosting/manage/productionchecklist.md
> +Use a appropriate Monitoring Solution to have an overview about your ZITADEL instance. In particular you may want to watch out for things like:
```suggestion
Use an appropriate monitoring solution to have an overview about your ZITADEL instance. In particular you may want to watch out for things like:
```

2023-01-17 11:27 UTC, eliobischof commented on docs/docs/self-hosting/manage/productionchecklist.md
> +- [ ] CPU and Memory of ZITADEL and the database
```suggestion
- [ ] CPU and memory of ZITADEL and the database
```

2023-01-17 11:27 UTC, eliobischof commented on docs/docs/self-hosting/manage/productionchecklist.md
> +- [ ] ZITADEL [Metrics](https://zitadel.com/docs/apis/observability/metrics)
```suggestion
- [ ] ZITADEL [metrics](https://zitadel.com/docs/apis/observability/metrics)
```

2023-01-17 16:04 UTC, eliobischof requested changes

2023-01-17 16:04 UTC, eliobischof commented on docs/docs/self-hosting/manage/productionchecklist.md
> +- [ ] configure a valid [SMTP Server](https://zitadel.com/docs/guides/manage/console/instance-settings#smtp) and test emails
```suggestion
- [ ] configure a valid [SMTP Server](/docs/guides/manage/console/instance-settings#smtp) and test emails
```

2023-01-17 16:04 UTC, eliobischof commented on docs/docs/self-hosting/manage/productionchecklist.md
> +- [ ] Add [Custom Branding](https://zitadel.com/docs/guides/manage/customize/branding) if required
```suggestion
- [ ] Add [Custom Branding](/docs/guides/manage/customize/branding) if required
```

2023-01-17 16:04 UTC, eliobischof commented on docs/docs/self-hosting/manage/productionchecklist.md
> +- [ ] configure a valid [SMS Service](https://zitadel.com/docs/guides/manage/console/instance-settings#sms) such as Twilio if needed
```suggestion
- [ ] configure a valid [SMS Service](/docs/guides/manage/console/instance-settings#sms) such as Twilio if needed
```

2023-01-17 16:04 UTC, eliobischof commented on docs/docs/self-hosting/manage/productionchecklist.md
> +- [ ] use a FQDN and a trusted valid certificate for external [TLS](https://zitadel.com/docs/self-hosting/manage/tls_modes#http2) connections
```suggestion
- [ ] use a FQDN and a trusted valid certificate for external [TLS](/docs/self-hosting/manage/tls_modes#http2) connections
```

2023-01-17 16:04 UTC, eliobischof commented on docs/docs/self-hosting/manage/productionchecklist.md
> +- [ ] ZITADEL [metrics](https://zitadel.com/docs/apis/observability/metrics)
```suggestion
- [ ] ZITADEL [metrics](/docs/apis/observability/metrics)
```

2023-01-23 12:24 UTC, livio-a approved these changes

2023-01-23 12:39 UTC, merged

2023-01-23 12:56 UTC, eliobischof commented on docs/docs/self-hosting/manage/productionchecklist.md
> +- [ ] configure a valid [SMS Service](https://zitadel.com/docs/guides/manage/console/instance-settings#sms) such as Twilio if needed
?

2023-01-23 12:56 UTC, eliobischof commented on docs/docs/self-hosting/manage/productionchecklist.md
> +- [ ] Use a Layer 7 Web Application Firewall to secure ZITADEL that supports **[HTTP/2](/docs/self-hosting/manage/http2)**
?