fix: add port to SMTP host label
zitadel/zitadel pull request #4980
Opened 2023-01-04 12:39 UTC by eliobischof

Closes #4737 

- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

2023-01-04 14:16 UTC, livio-a requested changes

2023-01-04 14:16 UTC, livio-a commented on internal/command/smtp.go
> +		}
please use an appropriate function like `net.SplitHostPort`, which will also correctly handle ipv6 addresses, ...

2023-01-04 14:16 UTC, livio-a commented on internal/command/smtp.go
> +		if strings.Count(hostAndPort, ":") != 1 {
please see above

2023-01-04 14:16 UTC, livio-a commented on internal/command/smtp_test.go
> +		},
maybe we could add a ipv6 test as well

2023-01-04 15:07 UTC, eliobischof commented
Good catch @livio-a, IPv6 is valid and tested now.
Did you also review the console changes, or should @peintnermax review that part?

2023-01-04 16:22 UTC, peintnermax commented
> Good catch @livio-a, IPv6 is valid and tested now. Did you also review the console changes, or should @peintnermax review that part?

Console changes look good to me 👍

2023-01-05 09:42 UTC, eliobischof commented
@peintnermax, FYI I just added the type=password attribute to the password component [7d4f09d](https://github.com/zitadel/zitadel/pull/4980/commits/7d4f09d4516b65063a1450dcc0efe084d0fee5f6)

2023-01-05 12:45 UTC, livio-a approved these changes
backend is now ok for me

2023-01-05 12:47 UTC, peintnermax commented
> @peintnermax, FYI I just added the type=password attribute to the password component [7d4f09d](https://github.com/zitadel/zitadel/pull/4980/commits/7d4f09d4516b65063a1450dcc0efe084d0fee5f6)

and autocomplete is not an issue or do we have to test this 🤔

2023-01-05 13:49 UTC, eliobischof commented
> and autocomplete is not an issue or do we have to test this thinking otherwise I would add a css class to show password field styling `-webkit-text-security: disc`

Good point! Can we live with this?

![image](https://user-images.githubusercontent.com/12727842/210794590-7bcb68b4-0c35-46df-beaa-430f3a456d46.png)

It's with type="password" and autocomplete="new-password".  I think it's the least bad solution: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#preventing_autofilling_with_autocompletenew-password.

I think it's better than showing the password and it's also better than `-webkit-text-security: disc`: https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-security

2023-01-05 14:06 UTC, eliobischof commented
I added the input attribute as decribed above https://github.com/zitadel/zitadel/pull/4980/commits/ac2200cf7df819f4420fed1764fb6a867b353171
I also fixed that the host field wasn't filled from remote data anymore https://github.com/zitadel/zitadel/pull/4980/commits/221212613c2c0d96905cf2d3517d3f95ee8eaff8

2023-01-12 11:28 UTC, eliobischof commented
@peintnermax, what do you think?

2023-01-12 12:49 UTC, peintnermax commented
IMO we should remove the type="password" and auto-complete attr as this could also prefill the field with the user password

2023-01-13 14:23 UTC, peintnermax commented
ok we should give this a try.. with new-password this should be fine 👍

2023-01-17 09:20 UTC, merged