feat(console): phone number validation with flags
zitadel/zitadel pull request #5139
Opened 2023-01-31 17:15 UTC by doncicuto

As an admin or end user I want to be able to enter my phone no matter of the format without it being refactored while typing.

Acceptance Criteria

- [X] I am able to enter spaces while entering my phone number
- [X] I can enter 00XX as country prefix (it changes when I click save)
- [X] I am able to enter 00 and a non swiss prefix
- [X] The number is not formatted while I enter it
- [X] The number is formatted when I click enter
- [X] I am able to choose the country prefix with a dropdown

A discussion about design issues and a video showing proposed behavior is available at [https://github.com/zitadel/zitadel/discussions/5115]([https://github.com/zitadel/zitadel/discussions/5115)

closes #3918 

- [X] I am happy with the code
- [X] Short description of the feature/issue is added in the pr description
- [X] PR is linked to the corresponding user story
- [X] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [X] No debug or dead code
- [X] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [X] Functionality of the acceptance criteria is checked manually on the dev system.

2023-02-01 15:00 UTC, peintnermax requested changes
Nice work. Just found some minor things 👍

2023-02-01 18:13 UTC, doncicuto commented on console/src/app/pages/users/user-create/user-create.component.ts
> +      // Try to parse number and format it according to country
Absolutely @peintnermax

2023-02-01 19:10 UTC, doncicuto commented on console/src/assets/i18n/it.json
> +      "COUNTRY": "Nazione"
Changed!

2023-02-01 19:10 UTC, doncicuto commented on console/src/assets/i18n/it.json
> +      "PHONE_HINT": "Utilizzare 00 o il simbolo + seguito dal prefisso del paese del chiamante, oppure selezionare il paese dall'elenco a discesa e infine inserire il numero di telefono",
Changed!

2023-02-01 19:10 UTC, doncicuto commented on console/src/assets/i18n/de.json
> +      "PHONE_HINT": "Verwenden Sie 00 oder das Symbol + gefolgt von der Landesvorwahl des Anrufers oder wählen Sie das Land aus der Dropdown-Liste aus und geben Sie schließlich die Telefonnummer ein"
Changed!

2023-02-01 19:12 UTC, doncicuto commented on console/src/app/pages/users/user-create/user-create.component.ts
> +      // Try to parse number and format it according to country
Now formatPhone is used in user-create.component.ts and edit-dialog.component.ts so code is now cleaner and reuses functionality

2023-02-02 05:31 UTC, juergrinaldi commented
@doncicuto Thanks a lot for your contribution. We'd love to send you a little 'thank you' via mail. If you're up for it, you can fill out this form.
https://docs.google.com/forms/d/1FCzRnM4fMmteosNuc-g1TxjG5BZlXlfYAfF1xvl-vFA

2023-02-02 08:35 UTC, peintnermax approved these changes

2023-02-02 08:36 UTC, merged