docs: typos in production checklist
zitadel/zitadel pull request #5155
Opened 2023-02-03 04:23 UTC by hifabienne

- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

2023-02-06 16:36 UTC, fforootd commented on docs/docs/self-hosting/manage/productionchecklist.md
> +- [ ] Make use of configuration management such as Terraform to provision all of the below
```suggestion
- [ ] Make use of configuration management tools such as Terraform to provision all of the below
```

2023-02-06 16:36 UTC, fforootd commented on docs/docs/self-hosting/manage/productionchecklist.md
> +- [ ] Secure your [masterkey](https://zitadel.com/docs/self-hosting/manage/configure)
```suggestion
- [ ] Keep your [masterkey](https://zitadel.com/docs/self-hosting/manage/configure) in a secure storage
```

2023-02-06 16:36 UTC, fforootd commented on docs/docs/self-hosting/manage/productionchecklist.md
> +- [ ] Make use of different service accounts to secure ZITADEL within your hyperscaler or Kubernetes
```suggestion
- [ ] Create service accounts for application that interacts with ZITADEL's APIs
```

2023-02-06 16:36 UTC, fforootd commented on docs/docs/self-hosting/manage/productionchecklist.md
> +- [ ] Make use of a CDN service if needed to ease maintainability and firewall/DNS/WAF configuration
```suggestion
- [ ] Make use of a CDN service to decrease the load for static assets served by ZITADEL
```

2023-02-06 16:36 UTC, fforootd commented on docs/docs/self-hosting/manage/productionchecklist.md
> +- [ ] Make use of a [security scanner](https://owasp.org/www-community/Vulnerability_Scanning_Tools) to test your application and cluster
```suggestion
- [ ] Make use of a [security scanner](https://owasp.org/www-community/Vulnerability_Scanning_Tools) to test your application and deployment environment
```

2023-02-10 07:33 UTC, hifabienne commented on docs/docs/self-hosting/manage/productionchecklist.md
> +- [ ] Use version control to store the provisioning
@thesephirot ping

2023-03-08 20:19 UTC, fforootd requested changes
@hifabienne I think removing the one line makes it ready to merge

2023-03-08 20:19 UTC, fforootd commented on docs/docs/self-hosting/manage/productionchecklist.md
> +- [ ] Use version control to store the provisioning
```suggestion
```

2023-03-24 09:13 UTC, fforootd approved these changes

2023-03-24 14:10 UTC, merged