feat: request users ordered by creation date
zitadel/zitadel pull request #5160
Opened 2023-02-04 10:39 UTC by doncicuto

As described by @peintnermax, this PR adds changes to request users ordered by creation date in backend (proto/grpc).

Also @juergrinaldi, in Zitadel console mat-sort-header has been added to the users list component so admins can sort users using that column. The following video shows sorting in action:

https://user-images.githubusercontent.com/30386061/216762418-6e7cbf19-db93-4d19-9da7-31bce7a6d64c.mp4

Closes #3360  

- [X] I am happy with the code
- [X] Short description of the feature/issue is added in the pr description
- [X] PR is linked to the corresponding user story
- [X] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [X] No debug or dead code
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [X] Functionality of the acceptance criteria is checked manually on the dev system.

2023-02-09 09:36 UTC, peintnermax requested changes
LGTM, but to pass the sorting column down to the request an additional case with `creationDate` is required here. Can you please add it? Thx
https://github.com/zitadel/zitadel/blob/6d1a8d425918db46dfcae467f1753268c7da08e5/console/src/app/pages/users/user-list/user-table/user-table.component.ts#L202

2023-02-09 19:23 UTC, doncicuto commented
Hi @peintnermax, I've added the missing case thanks for pointing me this issue out in https://github.com/zitadel/zitadel/pull/5160#pullrequestreview-1290744645

2023-02-17 12:33 UTC, livio-a approved these changes
backend LGTM and local test worked

@doncicuto thanks for the PR 😃

2023-02-17 12:34 UTC, peintnermax approved these changes

2023-02-17 13:15 UTC, merged