fix(actions): check allow to fail
zitadel/zitadel pull request #5197
Opened 2023-02-10 17:18 UTC by adlerhurst

```[tasklist]
### Definition of Ready
- [x] I am happy with the code
- [x] Short description of the feature/issue is added in the pr description
- [x] PR is linked to the corresponding user story
- [x] Acceptance criteria are met
- [x] All open todos and follow ups are defined in a new ticket and justified
- [x] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [x] No debug or dead code
- [x] Critical parts are tested automatically
- [x] Where possible E2E tests are implemented
- [x] Documentation/examples are up-to-date
- [x] All non-functional requirements are met
- [x] Functionality of the acceptance criteria is checked manually on the dev system.
```

2023-02-13 07:15 UTC, livio-a requested changes

2023-02-13 07:15 UTC, livio-a commented on internal/actions/actions.go
> +	}()
```suggestion
	var config *runConfig
	// only return the error if the function is not allowed to fail
	// in each case
	defer func() {
		if err != nil && config.allowedToFail {
			err = nil
		}
	}()
	config, err = prepareRun(ctx, ctxParam, apiParam, script, opts)
```

2023-02-13 07:15 UTC, livio-a commented on internal/actions/actions.go
> +	}()
to handle errors in the prepareRun as well

2023-02-14 16:37 UTC, eliobischof commented
Can we close this in favor of https://github.com/zitadel/zitadel/commit/c51315e2acbfdd5a9eb90d202ec95bd78748767c?

2023-02-17 14:26 UTC, merged