feat: add gitlab provider templates
zitadel/zitadel pull request #5405
Opened 2023-03-09 05:55 UTC by livio-a

Adds possibility to manage and use GitLab (incl. self hosted) template based providers

```[tasklist]
### Definition of Ready
- [x] I am happy with the code
- [x] Short description of the feature/issue is added in the pr description
- [x] PR is linked to the corresponding user story
- [x] Acceptance criteria are met
- [x] All open todos and follow ups are defined in a new ticket and justified
- [x] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [x] No debug or dead code
- [x] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [x] All non-functional requirements are met
- [x] Functionality of the acceptance criteria is checked manually on the dev system.
```

relates to #4432

2023-03-09 22:38 UTC, adlerhurst requested changes
I'm asking about azure because there is a package called azure

2023-03-09 22:38 UTC, adlerhurst commented on internal/idp/providers/oidc/oidc.go
> +func WithSelectAccount() ProviderOpts {
is the option not provided by azure?

2023-03-09 22:38 UTC, adlerhurst commented on internal/domain/policy_login.go
> +		IDPTypeAzureAD,
isn't azure implemented?

2023-03-09 22:38 UTC, adlerhurst commented on internal/domain/idp.go
> +		IDPTypeAzureAD:
isn't azure implemented?

2023-03-09 22:38 UTC, adlerhurst commented on internal/query/projection/idp_template_test.go
> +							expectedStmt: "INSERT INTO projections.idp_templates3 (id, creation_date, change_date, sequence, resource_owner, instance_id, state, name, owner_type, type, is_creation_allowed, is_linking_all
shouldn't this statement be always the same for all provider types?

2023-03-09 22:38 UTC, adlerhurst commented on internal/query/idp_template.go
> +)
```suggestion
)

```

2023-03-09 22:38 UTC, adlerhurst commented on internal/repository/idp/gitlab.go
> +	// return []*eventstore.EventUniqueConstraint{NewAddGitLabIDPConfigNameUniqueConstraint(e.Name, e.Aggregate().ResourceOwner)} // TODO: ?
todo

2023-03-09 22:38 UTC, adlerhurst commented on internal/repository/idp/gitlab.go
> +	Scopes       []string            `json:"scopes,omitempty"` // TODO: tristate?
todo

2023-03-09 22:38 UTC, adlerhurst commented on proto/zitadel/admin.proto
> +        option (google.api.http) = {
please add the openapi options

2023-03-09 22:38 UTC, adlerhurst commented on proto/zitadel/admin.proto
> +    string name = 1 [(validate.rules).string = {max_len: 200}];
@hifabienne please verify openapi options

2023-03-09 22:38 UTC, adlerhurst commented on proto/zitadel/idp.proto
> +        GitLabConfig gitlab = 9;
@hifabienne please verify openapi options

2023-03-09 22:38 UTC, adlerhurst commented on proto/zitadel/management.proto
> +    rpc AddGitLabProvider(AddGitLabProviderRequest) returns (AddGitLabProviderResponse) {
please add openapi option

2023-03-09 22:38 UTC, adlerhurst commented on proto/zitadel/management.proto
> +message AddGitLabProviderRequest {
please add openapi option

2023-03-10 15:37 UTC, peintnermax commented
@livio-a should the name attribute be required on self hosted or default to `Gitlab`?

2023-03-13 06:18 UTC, livio-a commented on internal/idp/providers/gitlab/gitlab_test.go
> +				AuthURL: "https://gitlab.com/oauth/authorize?client_id=clientID&redirect_uri=redirectURI&response_type=code&scope=openid&state=testState",
implemented

2023-03-13 06:19 UTC, livio-a commented on internal/domain/policy_login.go
> +		logging.Errorf("name of provider (type %v) is empty: %v", p.IDPConfigID, p.Type)
fixed (with correct field)

2023-03-13 06:19 UTC, livio-a commented on internal/command/org_idp_model.go
> +}
removed

2023-03-13 06:19 UTC, livio-a commented on internal/command/org_idp_model.go
> +}
removed

2023-03-13 09:52 UTC, adlerhurst reviewed
only errors remaining

2023-03-13 16:05 UTC, adlerhurst approved these changes

2023-03-13 16:08 UTC, adlerhurst commented on proto/zitadel/admin.proto
> +        option (google.api.http) = {
will be resolved in https://github.com/zitadel/zitadel/issues/5439

2023-03-13 16:08 UTC, adlerhurst commented on proto/zitadel/idp.proto
> +        GitLabConfig gitlab = 9;
will be resolved in https://github.com/zitadel/zitadel/issues/5439

2023-03-13 16:08 UTC, adlerhurst commented on proto/zitadel/management.proto
> +    rpc AddGitLabProvider(AddGitLabProviderRequest) returns (AddGitLabProviderResponse) {
will be resolved in https://github.com/zitadel/zitadel/issues/5439

2023-03-13 16:08 UTC, adlerhurst commented on proto/zitadel/management.proto
> +message AddGitLabProviderRequest {
will be resolved in https://github.com/zitadel/zitadel/issues/5439

2023-03-13 16:09 UTC, adlerhurst approved these changes

2023-03-13 16:34 UTC, merged