F internationalization japanese
zitadel/zitadel pull request #5443
Opened 2023-03-14 09:59 UTC by TakumiHaruta

## Description

Close #3990 

- Add Japanese translations to all i18n files

## Checklist

- [x] I am happy with the code
- [x] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [x] No debug or dead code
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

2023-03-17 08:26 UTC, hifabienne commented
Thanks @TakumiHaruta 
@zitadel/engineers can one of you have a look at this?

2023-03-17 10:56 UTC, peintnermax requested changes
I've found some lines we changed in the meantime and a faulty locale code.. Rest looks good thx for your work 👍 :)

2023-03-17 10:56 UTC, peintnermax commented on console/src/app/pages/org-create/org-create.component.ts
> +  public languages: string[] = ['de', 'en', 'fr', 'it', 'jp', 'pl', 'zh'];
Think this should be `ja` right?

2023-03-17 10:56 UTC, peintnermax commented on console/src/app/app.module.ts
> +import localeJp from '@angular/common/locales/ja';
```suggestion
import localeJa from '@angular/common/locales/ja';
```

2023-03-17 10:56 UTC, peintnermax commented on console/src/app/app.module.ts
> +registerLocaleData(localeJp);
```suggestion
registerLocaleData(localeJa);
```

2023-03-17 10:56 UTC, peintnermax commented on console/src/assets/i18n/ja.json
> +    }
```suggestion
    },
    "INVALID_FORMAT": "The formatting is invalid.",
    "NOTANEMAIL": "The given value is not an e-mail address.",
    "MINLENGTH": "Must be at least {{requiredLength}} characters long.",
    "UPPERCASEMISSING": "Must include an uppercase character.",
    "LOWERCASEMISSING": "Must include a lowercase character.",
    "SYMBOLERROR": "Must include a symbol or punctuation mark.",
    "NUMBERERROR": "Must include a digit.",
    "PWNOTEQUAL": "The passwords provided do not match.",
    "PHONE": "The phone number must start with 00 or +."
```

we had some new translations in the meantime.. could you set the correct values.. Thx

2023-03-17 10:56 UTC, peintnermax commented on console/src/assets/i18n/ja.json
> +      "NOTEQUAL": "入力されたパスワードが一致しません。"
```suggestion
      
```
got removed a in the meantime

2023-03-17 10:56 UTC, peintnermax commented on console/src/assets/i18n/ja.json
> +    },
```suggestion
```
got removed

2023-03-17 10:56 UTC, peintnermax commented on console/src/assets/i18n/ja.json
> +      },
```suggestion
      },
      "GITLAB": {
        "TITLE": "Gitlab Provider",
        "DESCRIPTION": "Enter the credentials for your Gitlab Identity Provider"
      },
      "GITLABSELFHOSTED": {
        "TITLE": "Gitlab Self Hosted Provider",
        "DESCRIPTION": "Enter the credentials for your Gitlab Self Hosted Identity Provider"
      },
```

can you please provide the japanese translations? thx

2023-03-17 10:56 UTC, peintnermax commented on console/src/assets/i18n/ja.json
> +      }
```suggestion
      },
      "AZUREAD": {
        "TITLE": "Microsoft Provider",
        "DESCRIPTION": "Enter the credentials for your Microsoft Identity Provider"
      }
```

2023-03-17 10:56 UTC, peintnermax commented on console/src/assets/i18n/ja.json
> +    },
```suggestion
    },
    "AZUREADTENANTTYPES": {
      "0": "Common",
      "1": "Organizations",
      "2": "Customers"
    },
    "AZUREADTENANTTYPE": "Tenant Type",
    "AZUREADTENANTID": "Tenant ID",
    "EMAILVERIFIED": "Email verified",
```

this was also added in the meantime

2023-03-18 05:41 UTC, TakumiHaruta commented
@peintnermax 
Thanks for reviewing. I fixed typo and updated translations. Please have a look again!

2023-03-20 07:12 UTC, peintnermax approved these changes
Looks good to me 👍

2023-03-20 07:24 UTC, hifabienne commented
@peintnermax can you please merge it when it is ok? external contributors are not able to do this.

2023-03-20 14:17 UTC, peintnermax commented
Could you please update your branch to fullfill our requirements to merge your PR or enable this setting on your account to let us do that: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork 
thx for your help! 👍

2023-03-21 07:33 UTC, TakumiHaruta commented
@peintnermax
I forked zitadel to github org account so there is no `Allow edits from maintainers` option.
Should I create a new PR from my private GitHub?

2023-03-21 09:48 UTC, peintnermax commented
> 

This would be great so we can update the branch 👍

2023-03-21 10:45 UTC, TakumiHaruta commented
@peintnermax 
I recreated PR in #5513
Please check it out!

2023-03-22 06:30 UTC, closed without merging

2023-03-29 07:43 UTC, livio-a commented
reviewe / basic test took me 15min