feat: add Help/Support e-mail for instance/org
zitadel/zitadel pull request #5445
Opened 2023-03-14 19:10 UTC by doncicuto

As an admin I am now able to set a help / support email address on the instance and the organisations, which is shown to the end users in the login.

Acceptance Criteria

- [X] I am able to set a help / support email on the instance
- [X] I am able to set a help / support email on the organisation
- [X] If a help / support email is set on the instance, I can see it in the login flow
- [X] If a help / support email is set on my organisation, I can see it in the login flow

Here are some screenshots
![instance_support_email](https://user-images.githubusercontent.com/30386061/225111477-42c5cfcf-c564-4ef8-839e-cdba0654b0ea.png)

![welcome_with_support_email](https://user-images.githubusercontent.com/30386061/225111529-9e8b3363-6a79-4d69-88a2-4f84976a2675.png)

![org_support_email](https://user-images.githubusercontent.com/30386061/225111600-fd7b05b9-5247-48c5-9c54-6f0336713d99.png)

![login_interface_text_footer](https://user-images.githubusercontent.com/30386061/225111632-f0a6737c-4605-4c52-aafc-df00141cfb9a.png)

![welcome_with_different_footer_email](https://user-images.githubusercontent.com/30386061/225111681-fc2a6fa5-f9aa-43ec-9673-8490a5c306f7.png)

This PR also fixes an issue where privacy policy links only could be assigned to instance, organizations where using instance defaults and those could not be overriden.

Closes #2526

```[tasklist]
### Definition of Ready
- [X] I am happy with the code
- [X] Short description of the feature/issue is added in the pr description
- [X] PR is linked to the corresponding user story
- [X] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [X] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [X] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [X] Functionality of the acceptance criteria is checked manually on the dev system.
```

2023-03-17 08:25 UTC, hifabienne commented
@zitadel/engineers can one of you have a look at this?

2023-03-17 08:27 UTC, hifabienne commented
Thanks @doncicuto we really appreciate all of your work

2023-03-23 11:21 UTC, eliobischof reviewed
LGTM :tada:  thank you a lot @doncicuto :pray: 
@peintnermax see my review comments. Thanks :slightly_smiling_face:

2023-03-27 15:52 UTC, peintnermax commented on console/src/app/modules/policies/privacy-policy/privacy-policy.component.html
> +    </cnsl-form-field>
yes. I'd use two grid columns such that we get a 2x2 layout. Can you change that please @doncicuto? Thx

2023-03-27 16:04 UTC, peintnermax commented on console/src/app/modules/settings-list/settings-list.component.html
> +    <cnsl-privacy-policy [serviceType]="serviceType"></cnsl-privacy-policy>
yes.. we have org and instance settings.. this is a bug fix actually. Thx @doncicuto 👍

2023-03-27 16:05 UTC, peintnermax requested changes
LGTM.. I'd just change the grid layout to two columns.. thx for the nice work 👍

2023-03-27 17:17 UTC, doncicuto commented
Thanks @peintnermax I'll change the grid layout as requested and update the PR once its finished

2023-03-28 18:28 UTC, doncicuto commented
Hi @peintnermax, this is the new 2x2 grid  layout. Updating PR @adlerhurst 

![image](https://user-images.githubusercontent.com/30386061/228333065-634f0101-a0a2-4b90-b6f4-a9c4be8f8668.png)

2023-03-28 19:36 UTC, peintnermax approved these changes
would not have made 75% width but it's fine 👍 thx

2023-03-28 19:36 UTC, merged

2023-03-29 12:06 UTC, eliobischof commented
Review and adjustments took ~3h