feat: ldap provider login
zitadel/zitadel pull request #5448
Opened 2023-03-15 08:21 UTC by stebenz

```[tasklist]
### Definition of Ready
- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.
```

2023-03-17 08:59 UTC, livio-a requested changes
please also update main and we can should have a look at the events version and unique constraints

2023-03-17 08:59 UTC, livio-a commented on internal/command/org_idp_test.go
>  				err: caos_errors.IsErrorInvalidArgument,
please check the new tests, where we check for the error id as well

2023-03-17 08:59 UTC, livio-a commented on internal/idp/providers/ldap/session.go
> +		if err != nil {
if multiple servers are configured, but the first server is not reachable, the user is not able to login

2023-03-17 08:59 UTC, livio-a commented on internal/idp/providers/ldap/session.go
> +		if err != nil {
generally the `try` should only handle connection errors to solve HA scenarios, right?

2023-03-17 08:59 UTC, livio-a commented on internal/query/idp_template.go
> +					Timeout:           ldapTimeout.Abs(),
why do we need an absolute value?

2023-03-17 08:59 UTC, livio-a commented on internal/api/ui/login/ldap_handler.go
> +			l.renderError(w, r, authReq, err)
```suggestion
			l.renderLDAPLogin(w, r, authReq, err)
			return
```

2023-03-17 08:59 UTC, livio-a commented on internal/api/ui/login/ldap_handler.go
> +		l.renderError(w, r, authReq, err)
```suggestion
		l.renderLDAPLogin(w, r, authReq, err)
```

2023-03-17 08:59 UTC, livio-a commented on internal/api/ui/login/ldap_handler.go
> +		l.renderError(w, r, authReq, err)
```suggestion
		l.renderLDAPLogin(w, r, authReq, err)
```

2023-03-17 10:13 UTC, stebenz commented on proto/zitadel/idp.proto
> +    Options provider_options = 10;
true, deleted

2023-03-17 10:16 UTC, stebenz commented on proto/zitadel/management.proto
> +    repeated string user_filters = 10 [(validate.rules).repeated = {max_items: 20, items: {string: {min_len: 1, max_len: 200}}}];
No, changed with min_items: 1

2023-03-17 10:18 UTC, stebenz commented on internal/query/projection/idp_template.go
> +			crdb.NewColumn(LDAPTimeoutCol, crdb.ColumnTypeInt64, crdb.Nullable()),
Besides the attributes non should be nullable, changed.

2023-03-20 06:53 UTC, livio-a requested changes
i think a short discussion would solve the last issues, incl. timeout

2023-03-20 06:53 UTC, livio-a commented on internal/api/ui/login/ldap_handler.go
> +			l.renderLDAPLogin(w, r, authReq, err)
```suggestion
			l.renderLDAPLogin(w, r, authReq, err)
			return
```

2023-03-20 06:53 UTC, livio-a commented on internal/idp/providers/ldap/session.go
> +		}
can we have a short discussion about this function, please?

2023-03-21 07:54 UTC, livio-a requested changes

2023-03-21 07:54 UTC, livio-a commented on internal/idp/providers/ldap/session.go
> +
please outsource that method. that way you're also able to defer correctly.
do we need to handle the parse error differently than the other errors?

2023-03-21 07:54 UTC, livio-a commented on internal/idp/providers/ldap/session.go
>  	timeout time.Duration,
timeout is never used

2023-03-21 07:54 UTC, livio-a commented on internal/idp/providers/ldap/session.go
>  	var emailVerified bool
i would put the mapping into a separate method, so you're able to test it as well

2023-03-21 07:54 UTC, livio-a commented on internal/idp/providers/ldap/session.go
> +	}
please add some tests for these functions

2023-03-21 07:54 UTC, livio-a commented on internal/idp/providers/ldap/session.go
> +	}
and i guess there's a better option to build the strings, please at least initialize the used array with a size

2023-03-24 15:18 UTC, merged