feat: Zitadel translated into Spanish
zitadel/zitadel pull request #5634
Opened 2023-04-07 14:47 UTC by doncicuto

Zitadel strings and messages translated into Spanish. Also some typos found in English files have been fixed.

Closes #5585 

```[tasklist]

### Definition of Ready

- [X] I am happy with the code
- [X] Short description of the feature/issue is added in the pr description
- [X] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [X] No debug or dead code
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [X] Functionality of the acceptance criteria is checked manually on the dev system.
```

2023-04-12 13:56 UTC, peintnermax requested changes
Thx for this amazing work.. Love to have spanish translations.. 🚀 console changes work and LGTM @eliobischof could you  take a look at the backend code?

2023-04-12 13:56 UTC, peintnermax commented on console/src/assets/i18n/es.json
> +    "DESCRIPTION": "Tu proceso de embarque",
found a missing translation from a recent PR..

2023-04-12 15:47 UTC, doncicuto commented on console/src/assets/i18n/es.json
> +    "DESCRIPTION": "Tu proceso de embarque",
Sure @peintnermax , I'll upload the missing translation today after work

2023-04-12 18:24 UTC, doncicuto commented on console/src/assets/i18n/es.json
> +    "DESCRIPTION": "Tu proceso de embarque",
Uploaded! Did a deeper search to find more missing translations. Thanks @peintnermax and @eliobischof as always for your reviewing time

2023-04-14 09:46 UTC, eliobischof requested changes

2023-04-14 09:46 UTC, eliobischof commented on internal/static/i18n/en.yaml
> +          removed: Font remove from label policy
```suggestion
          removed: Font removed from label policy
```

2023-04-14 09:46 UTC, livio-a requested changes
Hey @doncicuto we recently changed the mail templates to use the `DisplayName` instead of `FirstName` and `LastName` to be able to make them optional later on

2023-04-14 09:46 UTC, livio-a commented on internal/notification/static/i18n/es.yaml
> +  Greeting: Hola {{.FirstName}} {{.LastName}},
```suggestion
  Greeting: Hola {{.DisplayName}},
```

2023-04-14 09:46 UTC, livio-a commented on internal/notification/static/i18n/es.yaml
> +  Greeting: Hola {{.FirstName}} {{.LastName}},
```suggestion
  Greeting: Hola {{.DisplayName}},
```

2023-04-14 09:46 UTC, livio-a commented on internal/notification/static/i18n/es.yaml
> +  Greeting: Hola {{.FirstName}} {{.LastName}},
```suggestion
  Greeting: Hola {{.DisplayName}},
```

2023-04-14 09:46 UTC, livio-a commented on internal/notification/static/i18n/es.yaml
> +  Greeting: Hola {{.FirstName}} {{.LastName}},
```suggestion
  Greeting: Hola {{.DisplayName}},
```

2023-04-14 09:46 UTC, livio-a commented on internal/notification/static/i18n/es.yaml
> +  Greeting: Hola {{.FirstName}} {{.LastName}},
```suggestion
  Greeting: Hola {{.DisplayName}},
```

2023-04-14 09:46 UTC, livio-a commented on internal/notification/static/i18n/es.yaml
> +  Greeting: Hola {{.FirstName}} {{.LastName}},
```suggestion
  Greeting: Hola {{.DisplayName}},
```

2023-04-14 09:46 UTC, livio-a commented on internal/notification/static/i18n/es.yaml
> +  Greeting: Hola {{.FirstName}} {{.LastName}},
```suggestion
  Greeting: Hola {{.DisplayName}},
```

2023-04-14 09:54 UTC, eliobischof approved these changes

2023-04-14 13:02 UTC, peintnermax approved these changes

2023-04-14 13:53 UTC, livio-a approved these changes

2023-04-14 13:53 UTC, merged