feat: add ldap external idp to login api
zitadel/zitadel pull request #5938
Opened 2023-05-26 13:32 UTC by stebenz

### Definition of Ready

- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

2023-07-31 11:03 UTC, livio-a requested changes

2023-08-03 08:22 UTC, stebenz commented on proto/zitadel/user/v2alpha/user_service.proto
> +  ];
That's true, as in LDAP you have to have the credentials at the beginning, I will add an additional endpoint to set credentials again to reuse the intent.

2023-08-03 08:22 UTC, stebenz commented on internal/repository/idpintent/intent.go
> +	OAuthSucceededEventType = instanceEventTypePrefix + "oauth.succeeded"
Will change it back again.

2023-08-03 08:23 UTC, stebenz commented on internal/api/grpc/user/v2/user.go
> +		}, nil
Will move it to a function

2023-08-16 11:11 UTC, livio-a approved these changes

2023-08-16 11:29 UTC, merged