docs: Maintenance
zitadel/zitadel pull request #5993
Opened 2023-06-08 14:05 UTC by hifabienne

### Definition of Ready

- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

2023-06-08 15:28 UTC, mffap submitted a review, later dismissed
some small suggestions, would also be good to go now

2023-06-08 15:28 UTC, mffap commented on docs/docs/support/software-release-cycles-support.md
> +On ZITADEL Cloud we follow a regular deployment cycle to ensure our product remains up-to-date, secure, and provides new features.
```suggestion
ZITADEL Cloud follows a regular deployment cycle to ensure our product remains up-to-date, secure, and provides new features. 
```

2023-06-08 15:28 UTC, mffap commented on docs/docs/support/software-release-cycles-support.md
> +During these deployments, we strive to minimize any disruptions and do not expect any downtime.
```suggestion
During deployments, we strive to minimize any disruptions and do not expect any downtime.
```

2023-06-08 15:28 UTC, mffap commented on docs/docs/support/software-release-cycles-support.md
> +In rare situations where deploying a release carries a risk of downtime, we have a well-defined procedure in place to ensure transparent communication.
```suggestion
In rare situations where deploying releases that may  carry a risk of increased latency or short downtime, we have a well-defined procedure in place to ensure transparent communication. 
```

2023-06-08 15:28 UTC, mffap commented on docs/docs/support/software-release-cycles-support.md
> +We also recommend subscribing to those updates on the [status page](https://status.zitadel.com/).
```suggestion
We also recommend that you subscribe to those updates on the [status page](https://status.zitadel.com/).
```

2023-06-08 15:29 UTC, mffap commented
@hifabienne while we're here... do you want to include a link to the stable version in this pr? same page...

2023-06-09 08:51 UTC, hifabienne commented
> @hifabienne while we're here... do you want to include a link to the stable version in this pr? same page...

I added a section about the release types

2023-06-09 13:15 UTC, mffap requested changes

2023-06-09 13:15 UTC, mffap commented on docs/docs/support/software-release-cycles-support.md
> +
```suggestion
```

2023-06-12 06:27 UTC, mffap approved these changes

2023-06-16 08:51 UTC, merged