Feature BG
zitadel/zitadel pull request #5998
Opened 2023-06-09 11:37 UTC by dmushkov

Provides login, messages, and console in Bulgarian.
Adds missing language references to fr, it and zh where other languages are used.

- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

2023-06-13 12:33 UTC, peintnermax requested changes
Thx for your great work and your contribution. We have made some changes recently so can you please remerge main. Rest looks good to me 👍

2023-06-13 12:33 UTC, peintnermax commented on console/src/app/app.component.ts
> +    this.translate.addLangs(['de', 'en', 'es', 'fr', 'it', 'ja', 'pl', 'zh']);
can you remerge main branch and add it to supportedLanguages? Thx

2023-06-13 12:33 UTC, peintnermax commented on console/src/app/app.component.ts
> +        const fallbackLang = cropped.match(/de|en|es|fr|it|ja|pl|zh/) ? cropped : 'en';
same here and pls add `bg` to supported Languages

2023-06-16 13:28 UTC, eliobischof approved these changes

2023-06-16 13:35 UTC, peintnermax approved these changes
Thanks a lot for your contribution @dmushkov 🎉 

We appreciate your work and if you're interested we would send you some swag. Just send us a mail to [hi@zitadel.com](mailto:hi@zitadel.com). We will then send you a form with some questions about the shirt size and other details 👍

2023-06-16 15:35 UTC, merged