fix: back button in detail view should not navigate to create dialog again
zitadel/zitadel pull request #6018
Opened 2023-06-12 12:04 UTC by doncicuto

@mffap detected in #5069 that after creating a new client and go on the back button the create app dialog starts again.

This is a video showing the current situation:

https://github.com/zitadel/zitadel/assets/30386061/4a0f8b97-38b0-4f18-8452-1328a8922924

The same behavior should apper after creating a project, a user, a machine user and a project role. As a workaround once of those elements are created I suggest adding a query param: new=true. When the back directive is applied after clicking the back button if the new param exists, a new back navigation is performed so the create dialog is not shown. Maybe is not the most elegant solution with going back twice.

This is a video showing the proposed change:

https://github.com/zitadel/zitadel/assets/30386061/57bc2855-0725-4feb-b315-49d56dd1f22d

This PR should close #5069.

Acceptance Criteria
- [X] I land on the project detail when clicking back (<--) on the application detail
- [X] I land on the project detail when clicking back (<--) on the application detail when i just created the application

### Definition of Ready

- [X] I am happy with the code
- [X] Short description of the feature/issue is added in the pr description
- [X] PR is linked to the corresponding user story
- [X] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [X] No debug or dead code
- [X] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [X] Functionality of the acceptance criteria is checked manually on the dev system.

2023-06-12 12:10 UTC, hifabienne commented
@doncicuto Thanks for the pr.
@peintnermax can you have a look at it?

2023-06-13 15:20 UTC, peintnermax requested changes
nice work 👍 . I've just added a small change such that the subscription of the params is cancelled.

2023-06-13 16:06 UTC, doncicuto commented on console/src/app/directives/back/back.directive.ts
> +    this.route.queryParams.subscribe((params) => {
Change applied!

2023-06-13 16:07 UTC, doncicuto commented
Thanks a lot @peintnermax for your review, changes have been applied

2023-06-14 06:30 UTC, peintnermax approved these changes

2023-06-14 07:02 UTC, merged