feat: show all available organizations when creating project grants
zitadel/zitadel pull request #6040
Opened 2023-06-17 08:42 UTC by doncicuto

As an authorized Manager, I want see all available (to me) organizations so that I can create a project grant.

This is the proposed scenario where is no longer needed to enter the domain of the organization you want to grant (go to the organization detail page when you can't remember it):

https://github.com/zitadel/zitadel/assets/30386061/a5cee5cf-d5dc-4c28-b30c-663966d20362

Acceptance Criteria

- [X] All available organizations are shown (based on user authorizations) directly on the first screen
- [X] Search can filter for partial matches

Closes #5317 

### Definition of Ready

- [X] I am happy with the code
- [X] Short description of the feature/issue is added in the pr description
- [X] PR is linked to the corresponding user story
- [X] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [X] No debug or dead code
- [X] My code has no repetitions
- [ ] Critical parts are tested automatically
- [X] Where possible E2E tests are implemented
- [X] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [X] Functionality of the acceptance criteria is checked manually on the dev system.

2023-07-06 07:14 UTC, hifabienne commented
@peintnermax can you please have a look at this?

2023-07-07 06:53 UTC, peintnermax requested changes
As the `OrgQuery` is a one of, we need to provide an array.. The rest is amazing work. Thx 👍

2023-07-07 06:53 UTC, peintnermax commented on console/src/app/modules/search-org-autocomplete/search-org-autocomplete.component.ts
> +    this.auth.listMyProjectOrgs(undefined, 0, query ? [query] : undefined).then((orgs) => {
```suggestion
    this.auth.listMyProjectOrgs(undefined, 0, [query]).then((orgs) => {
```

lets clean this up a little

2023-07-07 06:53 UTC, peintnermax commented on console/src/app/modules/search-org-autocomplete/search-org-autocomplete.component.ts
> +          return from(this.auth.listMyProjectOrgs(undefined, 0, query ? [query] : undefined)).pipe(
```suggestion
          const stateQuery = new OrgQuery();

          const orgStateQuery = new OrgStateQuery();
          orgStateQuery.setState(OrgState.ORG_STATE_ACTIVE);
          stateQuery.setStateQuery(orgStateQuery);

          let queries: OrgQuery[] = [stateQuery];

          if (value) {
            const nameQuery = new OrgQuery();

            const orgNameQuery = new OrgNameQuery();
            orgNameQuery.setName(value);
            orgNameQuery.setMethod(TextQueryMethod.TEXT_QUERY_METHOD_CONTAINS_IGNORE_CASE);

            nameQuery.setNameQuery(orgNameQuery);
            queries = [stateQuery, nameQuery];
          }

          return from(this.auth.listMyProjectOrgs(undefined, 0, queries)).pipe(
```
`OrgQuery` is a one of so we need to create a seperate query for the name

2023-07-09 09:12 UTC, doncicuto commented
Thanks @peintnermax for your time reviewing my code. I've uploaded your requested changes

2023-07-17 13:26 UTC, doncicuto commented
Hi @peintnermax as GitHub still shows that there are pending requested changes, I'm not sure if you need me to do more changes to this PR. If that is the case, please let me know. Thanks as always

2023-07-18 06:38 UTC, peintnermax approved these changes

2023-07-18 06:45 UTC, merged