chore: add unit build tag
zitadel/zitadel pull request #6146
Opened 2023-07-05 13:38 UTC by eliobischof

### Definition of Ready

- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

2023-08-03 13:21 UTC, muhlemmer requested changes
Should we also mention in CONTRIBUTING.md that the user should setup the `unit` build flag in their IDE? 

For example `go.buildTags` setting for VSCode.

2023-08-05 11:49 UTC, eliobischof commented on build/zitadel/Dockerfile
> +    && go test -tags unit -race -coverprofile=profile.cov ./...
I updated main and made the relevant changes

2023-08-05 11:54 UTC, eliobischof commented on build/zitadel/Dockerfile
> +    && go test -tags unit -race -coverprofile=profile.cov ./...
Also, I enforced that all test files have either a unit or integration build tag in the make core_lint_custom recipe.

While doing so, I recognized, that the golangci-lint build-from-rev property only works as an argument, not in the config file and that git config diff.noprefix must not be true. I updated the makefile accordingly.

2023-08-08 09:54 UTC, muhlemmer requested changes
looks good. Just one empty file I'm not sure about if it should be there.

2023-08-08 09:54 UTC, muhlemmer commented on build/zitadel/generate-grpc.sh
empty file?

2023-08-08 10:33 UTC, eliobischof commented on build/zitadel/generate-grpc.sh
@adlerhurst, can we delete it?

2023-08-09 09:19 UTC, eliobischof commented on build/zitadel/generate-grpc.sh
The file is deleted

2023-08-11 08:58 UTC, muhlemmer submitted a review, later dismissed

2023-08-11 19:17 UTC, eliobischof commented
@livio-a can you please change the required checks and then merge the PR?

2023-08-15 08:16 UTC, livio-a requested changes
i this really the only solution... i doubt that this is maintainable

2023-08-15 13:42 UTC, eliobischof commented
> is this really the only solution? i doubt that this is maintainable

I can't think of a better solution to exclude the unit tests from integration test executions.
Build tags are constraints that can't be negated at compile time.
We could try to just grep the test files that have an integration build tag and only execute those. But enforcing to have build tags in test files and then run `go test -tags unit ./...` (or `integration`) feels more go-native and explicit to me. I'm open for suggestions, though.

`make core_lint_custom` ensures that the tags are maintained.

2023-10-12 14:47 UTC, muhlemmer commented
It seems this PR is stuck on the disagreement between @livio-a and @eliobischof. What is the way forward here? Are there other members in @zitadel/engineers that have an opinion perhaps?

2024-02-05 16:14 UTC, stebenz commented
@livio-a @eliobischof 
To pick up this discussion again, there is a possibility to mark the integration tests with 
```
// +build integration,!onlyunit
```
for example, as the negative flags in the command are not possible.

Anyway, we want to achieve that we can run unit and integration tests strictly separately right?

So we have to tag the test somehow, so I see the 3 options:
- tag integration tests so that we can exclude them
- tag unit tests so that we can include them if desired
- use the naming of the func's in the testfiles to differentiate the test-types (for example "TestIntegration_...")

I'm not quite sure which solution I find the best, but what are your thoughts?

2024-02-05 19:27 UTC, muhlemmer commented
> Anyway, we want to achieve that we can run unit and integration tests strictly separately right?

I think the disagreement comes from this assumption of "we".

For example I don't really care that some unit tests get an extra run in the pipeline. The time overhead is minimal compared to the test initialization and API calls of the integration tests. However, if there are people that think that exclusion is needed, I have nothing against it either.

Tl;Dr, my vote is neutral. And as far as I understand from previous review, @livio-a is against it.

2024-02-05 20:39 UTC, livio-a commented
> > Anyway, we want to achieve that we can run unit and integration tests strictly separately right?
> 
> I think the disagreement comes from this assumption of "we".
> 
> For example I don't really care that some unit tests get an extra run in the pipeline. The time overhead is minimal compared to the test initialization and API calls of the integration tests. However, if there are people that think that exclusion is needed, I have nothing against it either.
> 
> Tl;Dr, my vote is neutral. And as far as I understand from previous review, @livio-a is against it.

Yes, there apparently already is the first difference.

I totally see the point on only running unit test, resp. excluding certain tests in some cases, i.e. if they take more time to run, require dependencies, test more than the functionality itself (e.g. integration or benchmark test and so on)
Some of this was already achieved by the ’integration’ build flag. Another solution would be to use the ’testing.Short()’ function / ’go test -short’ flag for this. Obviously both patterns can be combined.

Maybe i missed something, but IMO the goal is to run the whole testsuite at the end / in CI. So why do we need to seperate the tests there, resp. why do we need to be able to exclude unit tests? As already mentioned by @muhlemmer, these shouldn't be really noticed anyway.
I am also still convinced that maintaining an additional build flag for unit tests (incl. making sure on every PR) is too much overhead.

2024-02-05 20:43 UTC, fforootd commented
While I am not fully briefed here my 2 cents from "far" away.

We should try to keep the mental overhead of maintaining test as low as possible and to me this sounds like something we will not maintain much when working on stuff so I would rather throw hardware at it (build times) then mental overhead 😁 

But please take a lot of salt with this comment.

2024-02-15 07:44 UTC, eliobischof commented
Closing in favor of which runs all the tests together in the pipeline https://github.com/zitadel/zitadel/pull/7388

2024-02-15 07:44 UTC, closed without merging