fix: add texts after template reset
zitadel/zitadel pull request #6237
Opened 2023-07-19 15:37 UTC by eliobischof

After template resets, new text set events were not emitted anymore.

### Definition of Ready

- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

2023-08-01 12:03 UTC, muhlemmer submitted a review, later dismissed

2023-08-01 12:09 UTC, muhlemmer requested changes
It seems that the unit tests need to be adjusted to handle the new event handling:

https://github.com/zitadel/zitadel/actions/runs/5713243265/job/15478370546?pr=6237#step:7:287

2023-08-03 10:44 UTC, eliobischof commented
> It seems that the unit tests need to be adjusted to handle the new event handling:
> 
> https://github.com/zitadel/zitadel/actions/runs/5713243265/job/15478370546?pr=6237#step:7:287

I fixed the unit test

2023-08-03 12:34 UTC, muhlemmer approved these changes

2023-08-04 18:12 UTC, merged