fix: avatar missing on login after going back
zitadel/zitadel pull request #6238
Opened 2023-07-19 19:26 UTC by doncicuto

In issue #1946 @mffap explained an issue where the avatar was missing after selecting a user, going back, and choosing the same user again. I reproduce the issue in the following video:

https://github.com/zitadel/zitadel/assets/30386061/5465fdf2-8dfc-443c-b041-70ecc54ea76c

In this PR DisplayName and AvatarKey are now added to the call of request.SetUserInfo triggered when this scenario happens. Now the avatar is shown:

https://github.com/zitadel/zitadel/assets/30386061/0e4960fa-1c14-4ebf-b934-bf3ba14114b2

Closes #1946 

### Definition of Ready

- [X] I am happy with the code
- [X] Short description of the feature/issue is added in the pr description
- [X] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [X] No debug or dead code
- [X] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [X] Functionality of the acceptance criteria is checked manually on the dev system.

2023-07-20 05:38 UTC, hifabienne commented
Thanks @doncicuto for the contribution. We will have a look at it.

2023-07-27 05:34 UTC, livio-a requested changes
The idea was that we only display the `DisplayName` and `Avatar` on existing sessions.
With the intended change, they would be display on new logins as well. This could disclose if the user exists, which would bad esp. for cases where `Ignore unknown usernames` is activated in the Login Policy.

But i had a quick look at the code. Couldn't we just set the two values after checking for the session in the `nextSteps` functions?
https://github.com/zitadel/zitadel/blob/48330fc4b1ffa44951baeb310627d4680a3c32d1/internal/auth/repository/eventsourcing/eventstore/auth_request.go#L952-L955
```diff
        userSession, err := userSessionByIDs(ctx, repo.UserSessionViewProvider, repo.UserEventProvider, request.AgentID, user)
        if err != nil {
                return nil, err
        }
+       request.DisplayName = userSession.DisplayName
+       request.AvatarKey = userSession.AvatarKey
```

2023-07-27 17:46 UTC, doncicuto commented
Thanks a lot @livio-a for your review, I'll try your suggestions tomorrow and change the PR accordingly.

2023-07-31 15:14 UTC, livio-a approved these changes

2023-08-10 14:19 UTC, merged