docs: add org scope to quickstart
zitadel/zitadel pull request #6261
Opened 2023-07-24 13:20 UTC by hifabienne

### Definition of Ready

- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

2023-07-27 12:36 UTC, dakshitha commented on docs/docs/guides/start/quickstart.mdx
> +## Show Organization Login
This part won't fit here because we do not cover audiences.

2023-07-28 06:29 UTC, dakshitha requested changes
Please see above comments.

2023-07-28 06:34 UTC, hifabienne commented
> https://zitadel.com/docs/guides/manage/console/organizations

Yes we can try that. Not sure if it is enough.

2023-07-28 06:49 UTC, hifabienne commented
I have changed it

2023-07-28 10:13 UTC, dakshitha approved these changes

2023-07-28 11:25 UTC, merged