fix(console): mdc components
zitadel/zitadel pull request #6482
Opened 2023-09-04 08:41 UTC by peintnermax

### Definition of Ready

- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

2023-09-19 20:01 UTC, eliobischof requested changes
The cypress tests fail

2023-09-25 13:56 UTC, peintnermax commented
> The cypress tests fail

e2e are fixed now 👍

2023-10-26 06:37 UTC, eliobischof approved these changes

2023-10-26 07:11 UTC, eliobischof approved these changes

2023-10-26 08:29 UTC, merged