docs: keycloak idp
zitadel/zitadel pull request #6568
Opened 2023-09-15 13:07 UTC by hifabienne

### Definition of Ready

- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

2023-09-15 13:31 UTC, mffap requested changes

2023-09-15 13:31 UTC, mffap commented on docs/docs/guides/integrate/identity-providers/keycloak.mdx
> +1. Login to your Keycloak Account and go to the clients list: <$KEYCLOAK-DOMAIN/auth/admin/$REALM/console/#/$REALM/clients>
```suggestion
1. Login to your Keycloak account and go to the clients list: <$KEYCLOAK-DOMAIN/auth/admin/$REALM/console/#/$REALM/clients>
```

2023-09-15 13:31 UTC, mffap commented on docs/docs/guides/integrate/identity-providers/keycloak.mdx
> +5. Add the Valid redirect URIs
```suggestion
5. Add the valid redirect URIs
```

2023-09-15 13:31 UTC, mffap commented on docs/docs/guides/integrate/identity-providers/keycloak.mdx
> +## ZITADEL Configuration
```suggestion
## ZITADEL configuration
```

2023-09-15 13:31 UTC, mffap commented on docs/docs/guides/integrate/identity-providers/keycloak.mdx
> +### Go to the IdP Providers Overview
```suggestion
### Go to the IdP providers overview
```

2023-09-15 13:31 UTC, mffap commented on docs/docs/guides/integrate/identity-providers/keycloak.mdx
> +### Create a new Generic OIDC Provider
```suggestion
### Create a new generic OIDC provider
```

2023-09-15 13:31 UTC, mffap commented on docs/docs/guides/integrate/identity-providers/keycloak.mdx
> +    issuer=": The domain of your Keycloak account and /auth/realms/$REALM, Example: https://lemur-0.cloud-iam.com/auth/realms/acme"
```suggestion
    issuer=": The domain where your Keycloak can be reached with the path /auth/realms/$REALM, Example: https://lemur-0.cloud-iam.com/auth/realms/acme"
```

2023-10-10 06:25 UTC, livio-a approved these changes
as all requested changes are solved, i'll just approve to get this out 😃

2023-10-11 04:56 UTC, merged