fix(backend): respect start flags in all commands
zitadel/zitadel pull request #6621
Opened 2023-09-25 14:36 UTC by dvob

Currently flags like `--externalDomain`, `--externalPort`, etc. do only work in the last added command which currently is `start-from-setup`. This change registers the flags to a global FlagSet in the init function in uses the FlagSet for all start commands.
The global FlagSet is not very nice but since the whole viper config stuff is already global this probably doesn't matter to much.

### Definition of Ready

- [ ] I am happy with the code
- [x] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [x] No debug or dead code
- [x] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

2023-11-23 09:51 UTC, hifabienne commented
hei @dvob 
I am sorry your PR absolutely slipped through.
We will have a look at it asap

2023-11-30 09:00 UTC, dvob commented
Now that I look at the changes again after some time, I probably still see a problem with my proposed solution.
In the init function where the start flags get registered viper is not yet initialized so the default values of the flags are not be displayed correctly. Maybe this is not really a problem because I think its the same behaviour for other flags (e.g. the tls settings).

I made another commit which removes the setting of the defaults. Because they would not work either way.

I guess to make this work the registering of the start flags should happen after viper is initialized which is probably after the OnInitialize function of Cobra did run (https://github.com/zitadel/zitadel/blob/79130b238b16bda0daa6d06431cd9f01c5639290/cmd/zitadel.go#L48).

2023-12-22 14:26 UTC, muhlemmer requested changes

2023-12-22 14:26 UTC, muhlemmer commented on cmd/start/flags.go
> +	externalPortFlag   = "externalPort"
I don't see much functional reason why these are moved into variables. It is cleaner, to read yes. But then I would suggest to make them contants. These values are never supposed to change.

2023-12-22 14:27 UTC, muhlemmer requested changes
Thanks for the PR. One small comment on flag name usage.

Can you also please run `go mod tidy` as `pflag` need to move from indirect to direct dep.

2024-01-04 10:04 UTC, hifabienne commented
hei @dvob 
Can you please have a look at the comments from @muhlemmer

2024-01-16 11:57 UTC, dvob commented
Sorry for my late response. @muhlemmer I did the changes you suggested.

2024-01-30 10:05 UTC, muhlemmer approved these changes

2024-02-21 10:12 UTC, muhlemmer submitted a review, later dismissed

2024-02-21 12:06 UTC, muhlemmer approved these changes

2024-02-21 12:26 UTC, merged