fix(cnsl): hide new auth button if no routerlink
zitadel/zitadel pull request #6640
Opened 2023-09-28 11:04 UTC by doncicuto

In #6290 Vladimir Logachev detected a bug where the New auth button was shown but clicking on it did nothing (as expected) for a simple user.

It seems that user.grant.write is not the only condition to hide that button in these situations, and I have checked that the button should be hidden if routerLink has no path set. A new showAddButton property is added.

In this screenshot the simple user no longer see the New button:

![image](https://github.com/zitadel/zitadel/assets/30386061/f8a02605-bd9f-4c32-804a-ea6793d05248)

Here Zitadel Admin can add new auths:

![image](https://github.com/zitadel/zitadel/assets/30386061/d441a5d6-14a4-47b1-ba38-de549820d66c)

### Note for reviewer

E2E every test run successfully with the exception of events/event.cy.ts which in my opinion has nothing to do with this code

Closes #6290

### Definition of Ready

- [X] I am happy with the code
- [X] Short description of the feature/issue is added in the pr description
- [X] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [X] No debug or dead code
- [X] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [X] Functionality of the acceptance criteria is checked manually on the dev system.

2023-09-28 11:36 UTC, peintnermax requested changes
Thx for your contribution! 👌I'd use the routerLink variable itself to check if it is set so we keep the loc to a minimum

2023-09-28 11:36 UTC, peintnermax commented on console/src/app/modules/user-grants/user-grants.component.html
> +    *ngIf="disableWrite === false && selection.hasValue() === false && showAddButton"
```suggestion
    *ngIf="disableWrite === false && selection.hasValue() === false && routerLink"
```

2023-09-28 11:36 UTC, peintnermax commented on console/src/app/modules/user-grants/user-grants.component.ts
> +  public showAddButton: boolean = false;
```suggestion
```

2023-09-28 11:36 UTC, peintnermax commented on console/src/app/modules/user-grants/user-grants.component.ts
> +          this.showAddButton = true;
```suggestion
```

2023-09-28 11:36 UTC, peintnermax commented on console/src/app/modules/user-grants/user-grants.component.ts
> +          this.showAddButton = true;
```suggestion
```

2023-09-28 11:36 UTC, peintnermax commented on console/src/app/modules/user-grants/user-grants.component.ts
> +          this.showAddButton = true;
```suggestion
```

2023-09-28 11:36 UTC, peintnermax commented on console/src/app/modules/user-grants/user-grants.component.ts
> +          this.showAddButton = true;
```suggestion
```

2023-09-28 11:36 UTC, peintnermax commented on console/src/app/modules/user-grants/user-grants.component.ts
> +        this.showAddButton = true;
```suggestion
```

2023-09-28 11:36 UTC, peintnermax commented on console/src/app/modules/user-grants/user-grants.component.html
> +    *ngIf="disableWrite === false && selection.hasValue() === false && showAddButton"
lets use the `routerLink` variable itself to check if the button should display or not

2023-09-28 11:38 UTC, peintnermax commented on console/src/app/modules/user-grants/user-grants.component.ts
> +  public showAddButton: boolean = false;
we have to initialize the routerLink with undefined in order to check it in the html.
```
public routerLink: any = undefined;
```

2023-09-28 12:21 UTC, doncicuto commented
You're right @peintnermax, your solution is prettier and cleaner

Thanks a lot... bug fixed 😄

2023-09-28 13:28 UTC, peintnermax commented
> You're right @peintnermax, your solution is prettier and cleaner
> 
> Thanks a lot... bug fixed 😄

Thx for your fast reaction 👍👍

2023-09-29 06:39 UTC, peintnermax approved these changes

2023-09-29 06:39 UTC, merged