feat(saml): option to create minimal SAML metadata file
zitadel/zitadel pull request #6671
Opened 2023-10-07 09:29 UTC by doncicuto

In #6507 @mffap proposed that:

> While creating a SAML application, I'm required to provide a metadata file. Not all providers expose this metadata file or it is clear where to find it. ZITADEL does not provide any guidance in the Wizard on what to do when the file is not available. [...] Allow users to provide ENTITYID and ACSURL with text fields and create the minimal metadata file on-the-fly [...]

This PR adds a new option when we create a SAML application (either wizard or pro mode) with two input fields for ENTITYID and ACSURL so a minimal metadata file is created on-the-fly. Also we've the same option available when we visit the app's detail.

Here's a video showing this new feature

https://github.com/zitadel/zitadel/assets/30386061/fd74176a-4c01-4738-9a0d-a688d13c49f1

Closes #6507 

### Definition of Ready

- [X] I am happy with the code
- [X] Short description of the feature/issue is added in the pr description
- [X] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [X] No debug or dead code
- [X] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [X] Functionality of the acceptance criteria is checked manually on the dev system.

2023-10-13 07:14 UTC, peintnermax requested changes
I've made some suggestions to react to changes of the new inputs and would slightly change some styling to have descriptions more consistent across the application.
Can you ensure that the suggestions out of the  `app-detail.component` are also applied the same way in `app-create.component`. The rest is very nice work.. thx @doncicuto 💯

2023-10-13 07:14 UTC, peintnermax commented on console/src/app/pages/projects/apps/app-create/app-create.component.html
> +                  <input cnslInput formControlName="acsURL" placeholder="https://" (change)="changeEntitityIdOrAcsURL()" />
```suggestion
                  <input cnslInput formControlName="acsURL" placeholder="https://" (change)="changeEntityIdOrAcsURL()" />
```

2023-10-13 07:14 UTC, peintnermax commented on console/src/app/pages/projects/apps/app-create/app-create.component.html
> +                  <input cnslInput formControlName="entityId" placeholder="https://" (change)="changeEntitityIdOrAcsURL()" />
```suggestion
                  <input cnslInput formControlName="entityId" placeholder="https://" />
```

2023-10-13 07:14 UTC, peintnermax commented on console/src/app/pages/projects/apps/app-create/app-create.component.html
> +                  <input cnslInput formControlName="entityId" placeholder="https://" (change)="changeEntitityIdOrAcsURL()" />
please use the `this.samlConfigForm.valueChanges.subscribe` in the ts file to react to changes so we can remove the `changeEntityIdOrAcsURL()`

2023-10-13 07:14 UTC, peintnermax commented on console/src/app/pages/projects/apps/app-create/app-create.component.ts
> +  }
please move this to `this.samlConfigForm.valueChanges.subscribe`. Thx 🙏

2023-10-13 08:45 UTC, doncicuto commented
Sure @peintnermax I'll prepare the changes today or tomorrow. Thanks for your review and the suggestions

2023-10-13 12:36 UTC, doncicuto commented on console/src/app/pages/projects/apps/app-detail/app-detail.component.html
> +              <span>{{ 'APP.SAML.METADATAOPT3' | translate }}</span>
I'll apply the same class to app-create.component.html

2023-10-16 08:00 UTC, peintnermax approved these changes
nice thx a lot @doncicuto 👍

2023-10-25 08:07 UTC, doncicuto commented
@eliobischof it seems that the FF test failed... if you want it to, I may try to test manually with latest Firefox in my machine that SMTP test and update the PR if that cypress test can be fixed/improved

2023-10-25 17:39 UTC, merged

2023-10-25 20:03 UTC, muhlemmer commented
> @eliobischof it seems that the FF test failed... if you want it to, I may try to test manually with latest Firefox in my machine that SMTP test and update the PR if that cypress test can be fixed/improved

#6811 as follow up. It is not caused by this PR. But feel free if you want to give it a shot :).