docs: Avg active idps
zitadel/zitadel pull request #7207
Opened 2024-01-12 12:25 UTC by hifabienne

Change legal description of active external identity providers

### Definition of Ready

- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

2024-01-12 12:26 UTC, hifabienne commented
should be merged after customer portal https://github.com/zitadel/website/pull/952

2024-01-13 09:08 UTC, mffap requested changes

2024-01-13 09:08 UTC, mffap commented on docs/docs/legal/service-description/billing.md
> +To calculate the monthly amount we summerize the activated external identity providers over all instances on each day and take the rounded up average over a given month.
```suggestion
To calculate the monthly amount we take the sum of activated external identity providers over all instances on each day and calculate the average over a given month, rounded up to the next integer.
```

2024-01-16 14:55 UTC, peintnermax approved these changes

2024-01-16 15:20 UTC, merged