docs: update flutter
zitadel/zitadel pull request #7214
Opened 2024-01-12 15:07 UTC by peintnermax

Based on https://github.com/zitadel/zitadel_flutter/pull/1

### Definition of Ready

- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

2024-08-15 18:57 UTC, eliobischof requested changes

2024-08-15 18:57 UTC, eliobischof commented on docs/docs/examples/login/flutter.md
> +https://github.com/zitadel/zitadel_flutter/blob/main/lib/main.dart#L115-L132
I think copying the code is more sustainable than referencing it, which IMO outweighs the DRY principle. What do you think?

2025-09-16 08:40 UTC, elinashoko commented
@peintnermax this has been hanging for a while, can you pls resolve conflicts/ merge?

2026-01-06 12:56 UTC, peintnermax commented
this PR is outdated

2026-01-06 12:56 UTC, closed without merging