docs(examples): adds java spring boot examples
zitadel/zitadel pull request #7226
Opened 2024-01-15 12:32 UTC by livio-a

### Definition of Ready

- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

2024-01-15 13:05 UTC, livio-a commented
@muhlemmer i've just added code highlighting for java (and php 😉 )

2024-01-15 17:46 UTC, muhlemmer requested changes

2024-01-15 17:46 UTC, muhlemmer commented on docs/docs/examples/secure-api/java-spring.md
> +> You can either create your own application or directly run the example by providing the necessary arguments.
```suggestion
:::info
This documentation references our [example](https://github.com/zitadel/zitadel-java) on GitHub.
You can either create your own application or directly run the example by providing the necessary arguments.
:::
```

2024-01-15 17:46 UTC, muhlemmer commented on docs/docs/examples/secure-api/java-spring.md
> +So in your application, create a 'support/zitadel' package and in there the `CustomAuthorityOpaqueTokenIntrospector.java`:
```suggestion
So in your application, create a `support/zitadel` package and in there the `CustomAuthorityOpaqueTokenIntrospector.java`:
```

2024-01-15 17:46 UTC, muhlemmer commented on docs/docs/examples/login/java-spring.md
> +> You can either create your own application or directly run the example by providing the necessary arguments.
```suggestion
:::info
This documentation references our [example](https://github.com/zitadel/zitadel-java) on GitHub. 
You can either create your own application or directly run the example by providing the necessary arguments.
:::
```

2024-01-15 17:46 UTC, muhlemmer commented on docs/docs/examples/login/java-spring.md
> +> If you are following along with the [example](https://github.com/zitadel/zitadel-java), set the dev mode to `true`, the Redirect URIs to `http://localhost:18080/webapp/login/oauth2/code/zitadel` an
```suggestion
:::info
If you are following along with the [example](https://github.com/zitadel/zitadel-java), set the dev mode to `true`, the Redirect URIs to `http://localhost:18080/webapp/login/oauth2/code/zitadel` and Post redirect URI to `http://localhost:18080/webapp`.
:::
```

2024-01-15 17:46 UTC, muhlemmer requested changes
Some formatting and info boxes.

2024-01-16 09:06 UTC, muhlemmer approved these changes

2024-01-16 10:07 UTC, livio-a commented
i've updated the code references (to main and removed the java/spring-boot folder)

2024-01-16 11:02 UTC, merged