docs: add US-1 region
zitadel/zitadel pull request #7230
Opened 2024-01-15 15:12 UTC by adlerhurst

### Definition of Ready

- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

2024-01-30 08:54 UTC, mffap requested changes

2024-01-30 08:54 UTC, mffap commented on docs/docs/legal/service-description/cloud-service-description.md
> +- **US-1**: Exclusively on US-1 (Iowa) region
```suggestion
- **US-1**: Exclusively hosted on regions in the United States
```

2024-11-04 11:26 UTC, mffap commented
@adlerhurst I would suggest that we completely remove this section. Rather have the available Cloud Regions somewhere more prominent on the website (eg, pricing page).

2024-11-06 11:02 UTC, adlerhurst commented
> @adlerhurst I would suggest that we completely remove this section. Rather have the available Cloud Regions somewhere more prominent on the website (eg, pricing page).
> 
> The section
> 

makes sense to me, its removed

2024-11-10 09:16 UTC, mffap approved these changes

2024-11-10 15:11 UTC, merged