docs: add EU-1 region
zitadel/zitadel pull request #7231
Opened 2024-01-15 15:13 UTC by adlerhurst

### Definition of Ready

- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

2024-01-30 08:57 UTC, mffap requested changes
I would not state the specific region here as this might change. Important information is in which geo-/political-regions the data is hosted. As a provider we should have the freedom to move within that region to optimize service delivery. More details can be provided on request.

2024-01-30 08:57 UTC, mffap commented on docs/docs/legal/service-description/cloud-service-description.md
> +- **US-1**: Exclusively on US-1 (Iowa) region
```suggestion
- **US-1**: Exclusively hosted on regions in the United States
```

2024-01-30 08:57 UTC, mffap commented on docs/docs/legal/service-description/cloud-service-description.md
> +- **EU-1**: Exclusively on EU-1 (Germany) region
```suggestion
- **EU-1**: Exclusively hosted on regions in the European Union
```

2024-11-02 10:43 UTC, adlerhurst commented
closed in favour of https://github.com/zitadel/zitadel/pull/7230

2024-11-02 10:43 UTC, closed without merging