docs: onboarding users
zitadel/zitadel pull request #7462
Opened 2024-02-28 12:50 UTC by hifabienne

Description on how to open the registration form directly in the login UI and about the registration options form.

### Definition of Ready

- [ ] I am happy with the code
- [x] Short description of the feature/issue is added in the pr description
- [x] PR is linked to the corresponding user story
- [x] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

2024-03-06 14:56 UTC, mffap requested changes
Some smaller suggetions and typos.

2024-03-06 14:56 UTC, mffap commented on docs/docs/guides/integrate/onboarding/end-users.mdx
> +As soon as the user clicks the "register" button, the registration options screen will be shown.
```suggestion
As soon as users click the "register" button, they will be presented with a screen showing the different registration options.
```

2024-03-06 14:56 UTC, mffap commented on docs/docs/guides/integrate/onboarding/end-users.mdx
> +The use can now select either local user registration or an external provider.
```suggestion
After that, the user can select either local user registration or an external provider.
```

2024-03-06 14:56 UTC, mffap commented on docs/docs/guides/integrate/onboarding/end-users.mdx
> +By pressing the button of an external provider, the user will directly be redirected to the provider.
```suggestion
By pressing the button of an external provider, the user will directly be redirected to the provider for consent.
```

2024-03-13 12:15 UTC, mffap requested changes
Should we, for completeness, include a short sentence about the organization scope to let users register to a pre-defined organization?

2024-03-13 12:15 UTC, mffap commented on docs/docs/guides/integrate/onboarding/end-users.mdx
> +OpenID Connect (OIDC) allows you to control the initial screen by sending a [prompt](/docs/apis/openidoauth/endpoints#additional-parameters) in the authorization request.
```suggestion
OpenID Connect (OIDC) allows you to control the initial screen by sending a [prompt](/docs/apis/openidoauth/endpoints#additional-parameters) parameter in the authorization request.
```

2024-03-13 12:15 UTC, mffap commented on docs/docs/guides/integrate/onboarding/end-users.mdx
> +With the `prompt=create` the registration form/options will directly be shown to the user.
```suggestion
With the `prompt=create`, the registration form/options will directly be shown to the user.
```

2024-03-13 12:15 UTC, mffap commented on docs/docs/guides/integrate/onboarding/end-users.mdx
> +If an organization does allow local user registration as well as registration with a social or enterprise login, the user will have to choose the option.
```suggestion
If an organization allows local user registration as well as registration with a social or enterprise login, the user can choose an option to register.
```

2024-03-13 14:47 UTC, hifabienne commented
> Should we, for completeness, include a short sentence about the organization scope to let users register to a pre-defined organization?

added

2024-03-14 07:51 UTC, mffap approved these changes

2024-03-14 08:25 UTC, merged