docs(legal): update cookies in privacy policy
zitadel/zitadel pull request #7493
Opened 2024-03-01 17:03 UTC by mffap

We will introduce google analytics to improve marketing and user experience analytics on our websites. Analytics is only done on our public website and the customer portal. We don't track behavior with Google Analytics on customer instances.

### Definition of Ready

- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

2024-03-04 09:58 UTC, fforootd reviewed
some small recommendations

2024-03-04 09:58 UTC, fforootd commented on docs/docs/legal/policies/privacy-policy.mdx
>  - Session management
```suggestion
- Session Management
```

2024-03-04 09:58 UTC, fforootd commented on docs/docs/legal/policies/privacy-policy.mdx
>  - Single Sign On
```suggestion
- Single Sign-On
```

2024-03-04 09:58 UTC, fforootd commented on docs/docs/legal/policies/privacy-policy.mdx
> +- Remembering preferences
```suggestion
- Remembering Preferences
```

2024-03-04 09:58 UTC, fforootd commented on docs/docs/legal/policies/privacy-policy.mdx
> +We don't use google analytics on customer instances of ZITADEL, but only on our public websites and customer portal.
```suggestion
We don't use google analytics on customer instances of ZITADEL, only on our public websites and customer portal.
```

2024-03-07 10:50 UTC, eliobischof requested changes

2024-03-07 10:50 UTC, eliobischof commented on docs/docs/legal/policies/privacy-policy.mdx
> +Last updated on March 01, 2024
```suggestion
Last updated on March 07, 2024
```

2024-03-07 11:07 UTC, eliobischof approved these changes

2024-03-07 11:35 UTC, merged