docs: external audit log
zitadel/zitadel pull request #7510
Opened 2024-03-06 10:06 UTC by hifabienne

### Definition of Ready

- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

2024-03-08 08:13 UTC, mffap requested changes

2024-03-08 08:13 UTC, mffap commented on docs/docs/guides/integrate/external-audit-log.md
> +For a detailed description please read the [Get Started Guide](https://www.cockroachlabs.com/docs/v23.2/create-and-configure-changefeeds) and [Cloud Storage Authentication](https://www.cockroachlabs.
```suggestion
For a detailed description please read [CockroachLab's Get Started Guide](https://www.cockroachlabs.com/docs/v23.2/create-and-configure-changefeeds) and [Cloud Storage Authentication](https://www.cockroachlabs.com/docs/v23.2/cloud-storage-authentication?filters=gcs#set-up-google-cloud-storage-assume-role) from Cockroach.
```

2024-03-08 08:13 UTC, mffap commented on docs/docs/guides/integrate/external-audit-log.md
> +```
```suggestion
```json lines
{
   "aggregate_id": "26553987123463875", 
   "aggregate_type": "user", 
   "created_at": "2023-12-25T10:01:45.600913Z", 
   "event_type": "user.human.added", 
   "instance_id": "123456789012345667", 
   "payload": null, 
   "sequence": 1
}
```
```

2024-03-08 08:13 UTC, mffap commented on docs/docs/guides/integrate/external-audit-log.md
> +```
```suggestion
```sql
CREATE CHANGEFEED INTO 'gs://gc-storage-zitadel-data/events?partition_format=flat&AUTH=specified&CREDENTIALS=base64encodedkey' 
AS SELECT instance_id, aggregate_type, aggregate_id, owner, event_type, sequence, created_at 
CASE WHEN event_type IN ('instance.domain.added', 'instance.domain.removed', 'instance.domain.primary.set' ) 
THEN payload END AS payload 
FROM eventstore.events2;
```
```

2024-03-08 08:13 UTC, mffap commented on docs/docs/guides/integrate/external-audit-log.md
> +  ```
```suggestion
```sql
CREATE CHANGEFEED INTO 'gs://gc-storage-zitadel-data/events?partition_format=flat&AUTH=specified&CREDENTIALS=base64encodedkey'
AS SELECT instance_id, aggregate_type, aggregate_id, owner, event_type, sequence, created_at 
FROM eventstore.events2;
```

2024-03-08 08:13 UTC, mffap commented on docs/docs/guides/integrate/external-audit-log.md
> +ZITADEL actions offer a powerful mechanism for extending the platform's capabilities and integrating with external systems tailored to your specific requirements.
```suggestion
ZITADEL [Actions](/docs/concepts/features/actions) offer a powerful mechanism for extending the platform's capabilities and integrating with external systems tailored to your specific requirements. 
```

2024-03-08 08:13 UTC, mffap commented on docs/docs/guides/integrate/external-audit-log.md
> +These actions are essentially custom JavaScript snippets that execute at predefined triggers during the registration or login flow of a user.
```suggestion
Actions are essentially custom JavaScript snippets that execute at predefined triggers during the registration or login flow of a user.
```

2024-03-08 08:13 UTC, mffap commented on docs/docs/guides/integrate/external-audit-log.md
> +In the future ZITADEL actions will be extended to allow to not only define them during the login and register flow, but also on each API Request, Event or Predefined Functions.
```suggestion
In the future ZITADEL Actions will be extended to allow to not only define them during the login and register flow, but also on each API Request, Event or Predefined Functions.
```

2024-03-08 08:13 UTC, mffap commented on docs/docs/guides/integrate/external-audit-log.md
> +### Webhook/API Request
```suggestion
### Webhook/API request
```

2024-03-08 08:13 UTC, mffap commented on docs/docs/guides/integrate/external-audit-log.md
> +Example Use Case:
```suggestion
Example use case:
```

2024-03-08 08:13 UTC, mffap commented on docs/docs/guides/integrate/external-audit-log.md
> +1. Define an action that calls API Endpoint.
```suggestion
1. Define an action that calls API endpoint.
```

2024-03-08 08:13 UTC, mffap commented on docs/docs/guides/integrate/external-audit-log.md
> +   Example how to call an API Endpoint:
```suggestion
   Example how to call an API endpoint:
```

2024-03-08 08:13 UTC, mffap commented on docs/docs/guides/integrate/external-audit-log.md
> +2. Add the action to the following Flows and Triggers
```suggestion
2. Add the action to the following flows and triggers
```

2024-03-08 08:13 UTC, mffap commented on docs/docs/guides/integrate/external-audit-log.md
> +3. Authenticate User
```suggestion
3. Authenticate user
```

2024-03-08 08:13 UTC, mffap commented on docs/docs/guides/integrate/external-audit-log.md
> +I want to send a request to an endpoint each time after an authentication (successful or not).
```suggestion
You want to send a request to an endpoint each time after an authentication (successful or not).
```

2024-03-08 11:19 UTC, mffap approved these changes

2024-03-11 13:35 UTC, stebenz approved these changes

2024-03-11 14:07 UTC, merged