docs: typescript login
zitadel/zitadel pull request #7621
Opened 2024-03-22 12:19 UTC by peintnermax

This PR improves the documentation about the new login UI

### Definition of Ready

- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

2024-03-27 14:24 UTC, livio-a requested changes

2024-03-27 14:24 UTC, livio-a commented on docs/docs/guides/integrate/login-ui/typescript-repo.mdx
> +The UI shows branding and behaves based on the policies and settings your instance or organization (when using an org scope) has.
```suggestion
The UI uses the branding and behaves based on the policies and settings of your instance or organization.
```

2024-03-27 14:24 UTC, livio-a commented on docs/docs/guides/integrate/login-ui/typescript-repo.mdx
> +It is also able to autenticate users without an OIDC context by navigating to the host of the login, to allow them to self service their account.
```suggestion
It is also allows users to authenticate directly (without an OIDC context) and self service their account.
```

2024-03-27 14:24 UTC, livio-a commented on docs/docs/guides/integrate/login-ui/typescript-repo.mdx
> +It's set of features will increase with time and its progress will be tracked [here](./typescript-repo#implemented-features).
```suggestion
Its set of features will increase with time and its progress will be tracked [here](./typescript-repo#implemented-features).
```

2024-03-27 14:24 UTC, livio-a commented on docs/docs/guides/integrate/login-ui/typescript-repo.mdx
> +The backend side of the application is authorized using a machine user and a personal access token.
```suggestion
The backend side of the application is authorized using a machine user's personal access token.
```

2024-03-27 14:24 UTC, livio-a commented on docs/docs/guides/integrate/login-ui/typescript-repo.mdx
> +The /loginname page allows to enter loginname or email of a user. User discovery is implemented at /api/loginname and if the user is found, redirected to the available authentication method page.
```suggestion
The /loginname page allows to enter loginname or email of a user. User discovery is implemented at /api/loginname and if the user is found, they will be redirected to the available authentication method page.
```

2024-03-27 14:24 UTC, livio-a commented on docs/docs/guides/integrate/login-ui/typescript-repo.mdx
> +If enough user information is retrieved and the user is authenticated, the flow is finalized by [requesting a the callback url](/docs/apis/resources/oidc_service/oidc-service-create-callback) for the
```suggestion
If enough user information is retrieved and the user is authenticated accorind to the policies, the flow is finalized by [requesting a the callback url](/docs/apis/resources/oidc_service/oidc-service-create-callback) for the auth request and the user is redirected back to the application.
```

2024-03-27 14:24 UTC, livio-a commented on docs/docs/guides/integrate/login-ui/typescript-repo.mdx
> +After authenticating, or with a valid session, users are able to self service their account.
```suggestion
Authenticated users are directly able to self service their account.
```

2024-03-27 14:24 UTC, livio-a commented on docs/docs/guides/integrate/login-ui/typescript-repo.mdx
> +Finally set your instance url as `ZITADEL_API_URL`. Make sure to set it without trailing slash.
we might need to add some images

2024-03-28 07:16 UTC, peintnermax commented on console/src/app/modules/accounts-card/accounts-card.component.ts
> +      scope: 'openid profile email urn:zitadel:iam:org:id:256088845584504464',
yes.. removed 👍

2024-03-28 07:27 UTC, peintnermax commented on docs/docs/guides/integrate/login-ui/typescript-repo.mdx
> +Finally set your instance url as `ZITADEL_API_URL`. Make sure to set it without trailing slash.
I've added a screenshot

2024-03-28 08:15 UTC, livio-a approved these changes

2024-03-28 08:19 UTC, merged