Allow using a local RSA key for machine keys
zitadel/zitadel pull request #7671
Opened 2024-03-28 13:50 UTC by aDogCalledSpot

Closes #7554 

Adds the option of using a locally generated RSA key for a machine key instead of having it generated by the server.
This prevents sending private keys over the network which is generally advised against.

A user can use the optional "pubkey" field of the request to send a public key. If a public key is specified, then no private key will be returned. If no public key is specified the behaviour is as before.

### Definition of Ready

- [x] I am happy with the code
- [x] Short description of the feature/issue is added in the pr description
- [x] PR is linked to the corresponding ~~user story~~ issue
- [ ] Acceptance criteria are met
- [ ] ~~All open todos and follow ups are defined in a new ticket and justified~~
- [ ] ~~Deviations from the acceptance criteria and design are agreed with the PO and documented~~
- [x] No debug or dead code
- [x] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [x] Documentation/examples are up-to-date
- [x] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

2024-03-28 13:55 UTC, aDogCalledSpot commented
@livio-a

2024-04-03 06:39 UTC, livio-a requested changes
Hey @aDogCalledSpot 

That already works perfectly 😃  
I'd change the proto slightly and think we should also check if the bytes provided can be parsed into an RSA public key.
This could be handled in:
https://github.com/zitadel/zitadel/blob/dff5984f7db1c5326cffc1ab32baf9cde882dcf3/internal/command/user_machine_key.go#L77-L83
with something like:
```go
if _, err := crypto.BytesToPublicKey(key.PublicKey); err != nil {
	return zerrors.ThrowInvalidArgument(nil, "COMMAND-5F3h1", "Errors.User.Machine.Key.Invalid")
}
```
And the translations for the new error `Errors.User.Machine.Key.Invalid` would then need to be added in https://github.com/zitadel/zitadel/blob/dff5984f7db1c5326cffc1ab32baf9cde882dcf3/internal/static/i18n/en.yaml#L108-L111 and the corresponding files.

2024-04-03 06:39 UTC, livio-a commented on proto/zitadel/management.proto
> +    bytes pubkey = 4;
```suggestion
    bytes public_key = 4 [
        (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
           example: "\"LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1...\"";
           description: "Optionally provide a public key of your own generated RSA private key.";
        }
    ];
```

2024-04-03 07:35 UTC, aDogCalledSpot commented
> return zerrors.ThrowInvalidArgument(nil, "COMMAND-5F3h1", "Errors.User.Machine.Key.Invalid")

Where does the ID `5F3h1` come from? Does it need to be documented anywhere?

2024-04-03 07:52 UTC, livio-a commented
> > return zerrors.ThrowInvalidArgument(nil, "COMMAND-5F3h1", "Errors.User.Machine.Key.Invalid")
> 
> Where does the ID `5F3h1` come from? Does it need to be documented anywhere?

That's randomly generated. You can just use it in that case.

2024-04-10 12:00 UTC, aDogCalledSpot commented
@livio-a can you re-review?

2024-04-18 07:04 UTC, aDogCalledSpot commented
Can we re-run the CI?

2024-04-22 08:28 UTC, aDogCalledSpot commented
> Can we re-run the CI?

bump

2024-04-22 09:29 UTC, livio-a commented
> > Can we re-run the CI?
> 
> bump

Sorry was on vacation. Just had a look at it. Can you also provide the translations for the other languages, please.

2024-04-22 11:44 UTC, livio-a commented
> > Can you also provide the translations for the other languages, please
> 
> I can provide it for German but otherwise all I could do is put it in google translate/deepL. Is that sufficient?

That's totally ok. I would need to do the same 😄

2024-04-23 09:10 UTC, livio-a approved these changes

2024-04-23 09:11 UTC, livio-a commented
@aDogCalledSpot thanks for this contribution. Really appreciated!
It will be released within this week 😃 
If you like to get a gift from us, please write an email to [hi@zitadel.com](mailto:hi@zitadel.com)

2024-04-23 09:38 UTC, merged