refactor(v2): init events
zitadel/zitadel pull request #7823
Opened 2024-04-22 13:23 UTC by adlerhurst

these events are used for later PRs

### Definition of Ready

- [x] I am happy with the code
- [x] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [x] No debug or dead code
- [x] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [x] Functionality of the acceptance criteria is checked manually on the dev system.

2024-05-13 13:30 UTC, livio-a requested changes

2024-05-22 07:34 UTC, adlerhurst commented on internal/v2/org/changed.go
> +	Name *string `json:"name,omitempty"`
changed to string

2024-05-22 07:34 UTC, adlerhurst commented on internal/v2/org/state.go
> +}
removed

2024-05-22 07:36 UTC, adlerhurst commented on internal/v2/user/human_registered.go
> +	StreetAddress     string              `json:"streetAddress,omitempty"`
removed

2024-05-22 07:36 UTC, adlerhurst commented on internal/v2/user/machine_secret_set.go
> +	// ClientSecret *crypto.CryptoValue `json:"clientSecret,omitempty"`
changed

2024-05-22 07:36 UTC, adlerhurst commented on internal/v2/user/human_init_code_added.go
> +	TriggeredAtOrigin string        `json:"triggerOrigin,omitempty"`
changed

2024-05-22 07:36 UTC, adlerhurst commented on internal/v2/user/human_password_changed.go
> +	// Secret            *crypto.CryptoValue `json:"secret,omitempty"`
changed

2024-05-22 07:36 UTC, adlerhurst commented on internal/v2/user/token_added.go
> +	PreferredLanguage language.Tag `json:"preferredLanguage"`
changed

2024-05-22 15:24 UTC, livio-a submitted a review, later dismissed

2024-05-23 04:36 UTC, livio-a approved these changes

2024-05-23 04:36 UTC, merged