fix: correct resourceowner of intent to instance
zitadel/zitadel pull request #7871
Opened 2024-04-29 13:14 UTC by stebenz

Currently the resourceowner is the organization of the user which is used to create the intent, this gets change to the instance with an optional organization, to check if the IDP is existing during the creation of the intent.

Closes #7656 

### Definition of Ready

- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

2024-05-01 08:30 UTC, livio-a commented
please have a look at the boxes, esp. the documentation one 😉

2024-05-01 09:00 UTC, stebenz commented
> please have a look at the boxes, esp. the documentation one 😉

Didn't know if we wanted to add an additional request example to the login example, but added it as well now.

2024-05-06 15:30 UTC, livio-a requested changes

2024-05-06 15:30 UTC, livio-a commented on internal/api/grpc/user/v2/user.go
> +	intent, err := s.command.GetIntentWriteModel(ctx, req.GetIdpIntentId(), authz.GetInstance(ctx).InstanceID())
```suggestion
	intent, err := s.command.GetIntentWriteModel(ctx, req.GetIdpIntentId(), "")
```

2024-05-07 05:42 UTC, livio-a approved these changes

2024-05-07 06:11 UTC, merged