Feat 4504
zitadel/zitadel pull request #7968
Opened 2024-05-16 09:29 UTC by doncicuto

# Which Problems Are Solved

- Zitadel doesn't have a way to test SMTP settings either before creating a new provider or once the SMTP provider has been created.
- Zitadel SMTP messages can be more informative for usual errors

# How the Problems Are Solved

- A new step is added to the new/update SMTP provider wizard that allows us to test a configuration. The result is shown in a text area.
- From the table of SMTP providers you can test your settings too.
- The email address to send the email is by default the email address for the logged in user as suggested.
- Some of the SMTP error messages have been changed to give more information about the possible situation. For example: could not contact with the SMTP server, check the port, firewall issues... instead of could not dial

Here's a video showing this new option in action:

https://github.com/zitadel/zitadel/assets/30386061/50128ba1-c9fa-4481-8eec-e79a3ca69bda

# Additional Changes

Replace this example text with a concise list of additional changes that this PR introduces, that are not directly solving the initial problem but are related.
For example:
- The docs explicitly describe that the property XY is mandatory
- Adds missing translations for validations.

# Additional Context

- Closes #4504

2024-05-22 16:26 UTC, stebenz commented on proto/zitadel/settings.proto
> +message SMTPTestResult {
Is this message used anywhere?

2024-05-22 16:26 UTC, stebenz commented on proto/zitadel/admin.proto
> +    string test_address = 7 [
Not quite sure, should we leave it like this or something like reciever_address?

2024-05-22 16:26 UTC, stebenz commented on internal/api/grpc/admin/smtp.go
> +	err := s.command.TestSMTPConfigById(ctx, resourceOwner, req.Id, req.TestAddress)
Can be combined with the 3 lines above, as it has to be changed anyway with logic changes.

2024-05-22 16:26 UTC, stebenz commented on internal/api/grpc/admin/smtp.go
> +	err := s.command.TestSMTPConfig(ctx, instanceID, req.Id, req.TestAddress, &config)
Same here with instanceID.

2024-06-12 13:04 UTC, doncicuto commented on proto/zitadel/settings.proto
> +message SMTPTestResult {
Thanks @stebenz, fixing it

2024-06-12 17:46 UTC, doncicuto commented
Hi @hifabienne, I think I've solved some issues so the review can be resumed

2024-06-20 13:24 UTC, eliobischof requested changes
Would you mind also adding the new Swedish translations?

2024-06-20 13:24 UTC, eliobischof commented on proto/zitadel/admin.proto
> +            description: "Test an SMTP provider identified by its is. After testing the provider, the users will receive information about the test results."
```suggestion
            description: "Test an SMTP provider identified by its ID. After testing the provider, the users will receive information about the test results."
```

2024-06-20 13:24 UTC, eliobischof commented on internal/static/i18n/en.yaml
> +    CouldNotAuth: could not add smtp auth, check if both your user and password are correct, if they're correct maybe your provider requires an auth method not supported by Zitadel
```suggestion
    CouldNotAuth: could not add smtp auth, check if both your user and password are correct, if they're correct maybe your provider requires an auth method not supported by ZITADEL
```

Can you correct this in the other files too, please?

2024-06-20 13:24 UTC, eliobischof commented on internal/static/i18n/de.yaml
> +    CouldNotAuth: Die SMTP-Authentifizierung konnte nicht hinzugefügt werden. Überprüfen Sie, ob sowohl Ihr Benutzername als auch Ihr Passwort korrekt sind. Wenn sie korrekt sind, erfordert Ihr Anbie
```suggestion
    CouldNotAuth: Die SMTP-Authentifizierung konnte nicht hinzugefügt werden. Überprüfen Sie, ob sowohl Ihr Benutzername als auch Ihr Passwort korrekt sind. Wenn sie korrekt sind, erfordert Ihr Anbieter möglicherweise eine Authentifizierungsmethode, die von ZITADEL nicht unterstützt wird
```

2024-06-20 13:24 UTC, eliobischof commented on console/src/app/modules/smtp-provider/smtp-provider.component.ts
> +        this.testResult = 'Your email was succesfully sent';
Can we translate this?

2024-06-20 13:49 UTC, doncicuto commented
Thanks @eliobischof I'll prepare the changes right away

2024-06-20 15:39 UTC, doncicuto commented
Hi @eliobischof I've updated the PR with your suggestions including Swedish translation. Thanks for your review!

2024-06-20 19:20 UTC, eliobischof approved these changes

2024-06-20 19:51 UTC, merged