docs(office-hours): add new resource api
zitadel/zitadel pull request #8077
Opened 2024-06-05 20:56 UTC by adlerhurst

Added new info for next office hours

2024-06-05 20:57 UTC, adlerhurst commented
FYI @mffap here is the next PR

2024-06-05 21:07 UTC, eliobischof requested changes

2024-06-05 21:07 UTC, eliobischof commented on MEETING_SCHEDULE.md
> +KUDOS, if you already have a look at our proposal before the start of the event. Share any inputs in the chat of the [office hours channel](https://zitadel.com/office-hours) on our Discord server.
```suggestion
KUDOS, if you already have a [look at our proposal](https://zitadel.com/docs/apis/v3) before the start of the event. Share any inputs in the chat of the [office hours channel](https://zitadel.com/office-hours) on our Discord server.
```

2024-06-05 21:15 UTC, eliobischof submitted a review, later dismissed

2024-06-06 06:11 UTC, eliobischof approved these changes

2024-06-06 10:16 UTC, merged