fix(oidc): store requested response_mode
zitadel/zitadel pull request #8145
Opened 2024-06-15 12:17 UTC by muhlemmer

# Which Problems Are Solved

Zitadel never stored or returned the requested `response_mode` in oidc Auth Requests. This caused the oidc library to fallback to the default based on the response_type.

# How the Problems Are Solved

- Store the `response_mode` in the Auth request repo
- Store the `response_mode` in the Auth request v2 events
- Return the `resonse_mode` from the application `ResponseMode()` methods. (Was hard-coded to an empty string)

# Additional Changes

- Populate the `response_modes_supported` to the oidc Discovery Configuration. When it was empty, the standard specifies the default of `query` and `fragment`. However, our oidc library also supports `form_post` and by this fix, zitadel now also supports this.

# Additional Context

- Closes #6586
- Reported https://discord.com/channels/927474939156643850/1151508313717084220

2024-06-15 13:11 UTC, muhlemmer commented
Regarding tests:

1. Query mode is the default and already covered by current tests
2. Fragments are never send over HTTP, therefore can't be tested automatically.
3. Form_post needs a user agent that executed the returned JavaScript snippet, therefore can be tested automatically.

I've manually tested the 3 modes using the v1 login. :ok_hand:

2024-06-17 05:33 UTC, livio-a approved these changes

2024-06-17 06:45 UTC, livio-a requested changes
Did not notice before, but looks like we also have a test for the discovery document, which now fails because of the exposed response modes: https://github.com/zitadel/zitadel/actions/runs/9542482426/job/26297420606?pr=8145#step:8:718

2024-06-17 09:20 UTC, livio-a approved these changes

2024-06-17 09:50 UTC, merged