fix: add details to ListUsers for user results
zitadel/zitadel pull request #8255
Opened 2024-07-05 11:56 UTC by stebenz

# Which Problems Are Solved

In User v2 API, the ListUsers endpoint doesn't provide the information to which organization the user belongs to.

# How the Problems Are Solved

Add the details to the user results from the ListUsers endpoint, so that the OrgID is also included as ResourceOwner.

# Additional Changes
 
None

# Additional Context

Closes #8172

2024-07-05 12:31 UTC, livio-a requested changes
how to we deal with the fact, that the userById now returns the details twice:
<img width="788" alt="image" src="https://github.com/zitadel/zitadel/assets/9405495/8718a953-f3ae-496c-9f0d-da50fcccb763">

2024-07-05 12:31 UTC, livio-a commented on internal/api/grpc/user/v2/query_integration_test.go
> +				fmt.Println(got.Result)
```suggestion
```

2024-07-05 13:58 UTC, stebenz commented on internal/api/grpc/user/v2/query_integration_test.go
> +				fmt.Println(got.Result)
removed

2024-07-05 13:59 UTC, stebenz commented
@livio-a saw that as well, was the reason that the test failed, I corrected it and removed it from the GetUserByIDResponse, so that the returned User message is consistent.

2024-07-10 13:58 UTC, stebenz commented
as mentioned here https://github.com/zitadel/zitadel/issues/8172#issuecomment-2211098049 if the orgID is provided and the passwordChangeRequired already is available in the user v2 calls, this should also be solved

2024-07-10 14:45 UTC, livio-a approved these changes

2024-07-10 15:49 UTC, merged