feat: add delete phone endpoint to v2 api
zitadel/zitadel pull request #8321
Opened 2024-07-16 19:34 UTC by jbiscoglia-klaviyo

# Which Problems Are Solved

- Adds delete phone endpoint to v2 api

# How the Problems Are Solved

- Adds new endpoint with DELETE method to /v2beta/users/:userId/phone which removes currently set phone number

# Additional Changes

- Added integration test for new endpoint.

# Additional Context

Replace this example with links to related issues, discussions, discord threads, or other sources with more context.
Use the Closing #issue syntax for issues that are resolved with this PR.
- Solves https://discord.com/channels/927474939156643850/1255557862286032996

2024-07-17 16:27 UTC, stebenz requested changes

2024-07-17 21:26 UTC, jbiscoglia-klaviyo commented on internal/api/grpc/user/v2/phone_integration_test.go
> +		{
Added those tests plus one for a missing user id. I'm throwing a phone not found error if the user has either already removed their phone or has never set one. Let me know if I should do something different.

2024-07-18 13:07 UTC, jbiscoglia-klaviyo commented on internal/api/grpc/user/v2/phone_integration_test.go
> +		{
Good catch. Should be good now

2024-07-19 06:00 UTC, stebenz commented on internal/api/grpc/user/v2/phone_integration_test.go
> +		{
Technically it works like this, but I would prefer it that you have the dependencies in the tests and no condition dependent on a string.
Just as an example, have a look in the [query_integration_test.go](https://github.com/zitadel/zitadel/blob/0ea3c5691f420fbb9644a9b2c7e5fc65aadebd3b/internal/api/grpc/user/v2/query_integration_test.go#L26).

2024-07-19 13:59 UTC, jbiscoglia-klaviyo commented on internal/api/grpc/user/v2/phone_integration_test.go
> +		{
Should be good now

2024-07-24 07:39 UTC, eliobischof approved these changes
Hi @jbiscoglia-klaviyo 
Thanks a lot for this helpful feature, we really appreciate it.
If you would like to get a small gift from us, please reach out to hi@zitadel.com

2024-07-24 08:20 UTC, eliobischof commented
@jbiscoglia-klaviyo can you please merge back main or allow me to push to the PR?

2024-07-24 13:34 UTC, jbiscoglia-klaviyo commented
Not sure why the e2e test failed. I think it might be a flaky test and I made no changes to the console. @eliobischof Are you able to manually re-run the workflow?

2024-07-24 13:46 UTC, merged