docs: update oidc-playground link
zitadel/zitadel pull request #8529
Opened 2024-09-02 09:26 UTC by peintnermax

The new OIDC playground is deployed on https://zitadel.com/oidc-playground.
This PR updates the relative links in the docs

2024-09-02 12:10 UTC, hifabienne commented
@peintnermax i think there should also change something in the sidebar right? 
when i look at the preview now, i still see the same as before

2025-02-26 15:48 UTC, peintnermax commented
> @peintnermax i think there should also change something in the sidebar right? when i look at the preview now, i still see the same as before

this is fixed now and can be reviewed again

2025-02-26 15:52 UTC, hifabienne approved these changes

2025-02-27 11:11 UTC, peintnermax commented
@fforootd https://github.com/zitadel/website/pull/1256 this is required

2025-02-27 12:10 UTC, fforootd requested changes
I made some changes/comments.

Generally speaking, we should discuss lint settings here. Its not so nice to review a PR with a lot of lint changes that just should change links 😁

2025-02-27 12:10 UTC, fforootd commented on docs/docs/apis/introduction.mdx
> +The [OIDC Playground](/oidc-playground) is for testing OpenID authentication requests and their parameters.
```suggestion
The [OIDC Playground](/playgrounds/oidc) is for testing OpenID authentication requests and their parameters.
```

2025-02-27 12:10 UTC, fforootd commented on docs/docs/guides/integrate/identity-providers/_test_setup.mdx
> +or [use the ZITADEL OIDC Playground](/oidc-playground) to see what happens with the login when you send different scopes.
```suggestion
or [use the ZITADEL OIDC Playground](/playgrounds/oidc) to see what happens with the login when you send different scopes.
```

2025-02-27 12:10 UTC, fforootd commented on docs/docs/guides/integrate/login/login-users.mdx
> +Authenticating users through the OpenID Connect protocol typically requires an application to redirect the user with an [Auth Request](/docs/oidc-playground) to the identity provider that contains in
```suggestion
Authenticating users through the OpenID Connect protocol typically requires an application to redirect the user with an [Auth Request](/playgrounds/oidc) to the identity provider that contains information such as the requesting application, [scopes](/docs/apis/openidoauth/scopes), and redirect url.
```

2025-02-27 12:10 UTC, fforootd commented on docs/docs/guides/integrate/login/oidc/authmethods/_basic.mdx
> +Try out the request in our [OIDC Authentication Request Playground](/oidc-playground?auth_method=Client%20Secret%20Basic).
```suggestion
Try out the request in our [OIDC Authentication Request Playground](/playgrounds/oidc?auth_method=Client%20Secret%20Basic).
```

2025-02-27 12:10 UTC, fforootd commented on docs/docs/guides/integrate/login/oidc/authmethods/_jwtpk.mdx
> +Try out the request in our [OIDC Authentication Request Playground](/oidc-playground?auth_method=Client%20Secret%20Basic).
```suggestion
Try out the request in our [OIDC Authentication Request Playground](/playgrounds/oidc?auth_method=Client%20Secret%20Basic).
```

2025-02-27 12:10 UTC, fforootd commented on docs/docs/guides/integrate/login/oidc/authmethods/_pkce.mdx
> +Try out the request in our [OIDC Authentication Request Playground](/oidc-playground).
```suggestion
Try out the request in our [OIDC Authentication Request Playground](/playgrounds/oidc).
```

2025-02-27 12:10 UTC, fforootd commented on docs/docs/guides/integrate/onboarding/end-users.mdx
> +You can test the impact of the different prompts on your login UI in our [OIDC Playground](/docs/oidc-playground).
```suggestion
You can test the impact of the different prompts on your login UI in our [OIDC Playground](/playgrounds/oidc).
```

2025-02-27 12:10 UTC, fforootd commented on docs/docs/guides/manage/console/default-settings.mdx
> +If there is no [auth request](https://zitadel.com/docs/oidc-playground), users will be redirected to the Default Redirect URI, which is by default `https://<custom_domain>/ui/console/`
```suggestion
If there is no [auth request](/playgrounds/oidc), users will be redirected to the Default Redirect URI, which is by default `https://<custom_domain>/ui/console/`
```

2025-02-27 12:10 UTC, fforootd commented on docs/docs/guides/manage/console/organizations.mdx
> +Read more about the [scopes](/docs/apis/openidoauth/scopes#reserved-scopes) or try it out in our [OIDC Playground](/docs/oidc-playground).
```suggestion
Read more about the [scopes](/docs/apis/openidoauth/scopes#reserved-scopes) or try it out in our [OIDC Playground](/playgrounds/oidc).
```

2025-02-27 12:10 UTC, fforootd commented on docs/docs/guides/manage/customize/branding.md
> +You can use our [OpenID Authentication Request Playground](/oidc-playground) to learn more about how to trigger an [organization's policies and branding](/oidc-playground#organization-policies-and-br
```suggestion
You can use our [OpenID Authentication Request Playground](/playgrounds/oidc) to learn more about how to trigger an [organization's policies and branding](/oidc-playground#organization-policies-and-branding).
```

2025-02-27 12:10 UTC, fforootd commented on docs/docs/guides/manage/customize/branding.md
> +You can use our [OpenID Authentication Request Playground](/oidc-playground) to learn more about how to trigger an [organization's policies and branding](/oidc-playground#organization-policies-and-br
I guess the second part of the link should be also different -> [organization's policies and branding](/oidc-playground#organization-policies-and-branding).

2025-02-27 12:10 UTC, fforootd commented on docs/docs/guides/manage/customize/user-metadata.md
> +Use the [OIDC authentication request playground](/docs/oidc-playground) or the configuration of an [example client](/docs/sdk-examples/introduction) to set the required scopes and receive a valid acc
```suggestion
Use the [OIDC authentication request playground](/playgrounds/oidc) or the configuration of an [example client](/docs/sdk-examples/introduction) to set the required scopes and receive a valid access token.
```

2025-02-27 12:10 UTC, fforootd commented on docs/docs/guides/manage/customize/user-metadata.md
> +Use the [OIDC authentication request playground](/docs/oidc-playground) or the configuration of an [example client](/docs/sdk-examples/introduction) to set the required scopes and receive a valid acc
```suggestion
Use the [OIDC authentication request playground](/playgrounds/oidc) or the configuration of an [example client](/docs/sdk-examples/introduction) to set the required scopes and receive a valid access token.
```

2025-02-27 12:10 UTC, fforootd commented on docs/docs/guides/migrate/introduction.md
> +- Redirect migrated users with a login hint in the [auth request](/docs/oidc-playground) to ZITADEL to pre-select the user
Are you sure you want to change that one?

2025-02-27 12:10 UTC, fforootd commented on docs/docs/guides/solution-scenarios/domain-discovery.mdx
> +You can also configure these settings on the default organization (see below) and send the scope `urn:zitadel:iam:org:id:{id}` with every [auth request](/docs/oidc-playground#organization-policies-an
Are you sure you want to change that one?

2025-02-27 12:10 UTC, fforootd commented on docs/sidebars.js
> +              href: "https://zitadel.com/oidc-playground",
```suggestion
              href: "/playgrounds/oidc",
```

2025-02-27 12:10 UTC, fforootd commented on docs/sidebars.js
> +              href: "https://zitadel.com/oidc-playground",
not sure if this works

2025-02-27 12:10 UTC, fforootd commented on docs/src/components/authrequest.jsx
> +      text={`https://zitadel.com/docs/oidc-playground?instance=${encodeURIComponent(
```suggestion
      text={`https://zitadel.com/playgrounds/oidc?instance=${encodeURIComponent(
```

2025-02-27 12:10 UTC, fforootd commented on docs/src/components/authrequest.jsx
> +      text={`https://zitadel.com/docs/oidc-playground?instance=${encodeURIComponent(
I guess dynamic loading the host would be nicer, but not important

2025-03-03 08:44 UTC, peintnermax commented on docs/sidebars.js
> +              href: "https://zitadel.com/oidc-playground",
lets check it in the preview

2025-03-03 08:44 UTC, fforootd commented on docs/sidebars.js
> +              href: "https://zitadel.com/oidc-playground",
works for me 😁

2025-03-03 08:50 UTC, peintnermax commented on docs/docs/guides/migrate/introduction.md
> +- Redirect migrated users with a login hint in the [auth request](/docs/oidc-playground) to ZITADEL to pre-select the user
this should be fine. it is /playgrounds/oidc now

2025-03-03 13:06 UTC, fforootd commented
> @fforootd the relative path `/playgrounds/oidc` does not work as it is relative to /docs and ends up being /docs/playgrounds/oidc. I'll set it to an absolute path everywhere

Ok, noted

2025-03-03 13:07 UTC, fforootd commented on docs/docs/guides/manage/customize/user-metadata.md
> +Use the [OIDC authentication request playground](/docs/oidc-playground) or the configuration of an [example client](/docs/sdk-examples/introduction) to set the required scopes and receive a valid acc
@peintnermax bump

2025-03-03 13:20 UTC, peintnermax commented on docs/docs/guides/solution-scenarios/domain-discovery.mdx
> +You can also configure these settings on the default organization (see below) and send the scope `urn:zitadel:iam:org:id:{id}` with every [auth request](/docs/oidc-playground#organization-policies-an
ok removed 👍

2025-03-03 13:24 UTC, fforootd commented
> > @fforootd the relative path `/playgrounds/oidc` does not work as it is relative to /docs and ends up being /docs/playgrounds/oidc. I'll set it to an absolute path everywhere
> 
> Ok, noted

I think relative would work if you transit one level up so ../playgrounds/oidc

2025-03-03 13:39 UTC, fforootd approved these changes
Not a fan of that fixed link to zitadel.com but we can bite the bullet

2025-03-03 13:54 UTC, merged