docs: change recommendation from cockroachDB to postgreSQL
zitadel/zitadel pull request #8844
Opened 2024-10-30 10:39 UTC by hifabienne

# Which Problems Are Solved

As we switched to PostgreSQL with our cloud zitadel, we now want to recommend it instead of CockroachDB.

# How the Problems Are Solved

Replaced the recommend section with postgresql

2024-10-30 17:18 UTC, muhlemmer requested changes

2024-10-30 18:26 UTC, hifabienne commented
@muhlemmer thanks will fix them.
Quick question, do I see it correctly that the default is still cockroach in self hosting, but our recommendation is postgresql? Asking because i want to know if i need to change the text on this page: https://zitadel.com/docs/self-hosting/manage/database#zitadel-with-postgres

2024-10-31 09:18 UTC, muhlemmer commented
Yeah.. If we change defaults.yaml it will be a breaking change. We didn't want to touch that yet.

2024-10-31 09:21 UTC, muhlemmer approved these changes

2024-10-31 09:24 UTC, merged