docs: init benchmarks
zitadel/zitadel pull request #8894
Opened 2024-11-12 08:43 UTC by adlerhurst

# Which Problems Are Solved

Adds initial benchmarks.

# How the Problems Are Solved

Added section `apis/benchmarks`

# Additional Changes

Update Makefile dependencies

# Additional Context

- Part of https://github.com/zitadel/zitadel/issues/8023
- Part of https://github.com/zitadel/zitadel/issues/8352

2024-11-13 07:33 UTC, hifabienne commented on docs/docs/apis/benchmarks/_template.mdx
> +## Test results
Just thought i would probably search for performance test, so we have that in the index
```suggestion
## Performance test results
```

2024-11-13 07:33 UTC, hifabienne commented on docs/docs/apis/benchmarks/v2.65.0/machine_jwt_profile_grant/index.mdx
> +## Test results
```suggestion
## Performance test results
```

2024-11-14 14:33 UTC, muhlemmer requested changes
Nice work! No comments from my side. Can you please implement the comments provided by @hifabienne  and then we can approve / merge.

2024-11-15 21:44 UTC, muhlemmer approved these changes

2024-11-15 21:44 UTC, merged