feat: add saml request to link to sessions
zitadel/zitadel pull request #9001
Opened 2024-12-03 09:56 UTC by stebenz

# Which Problems Are Solved

Replace this example text with a concise list of problems that this PR solves.
For example:
- If the property XY is not given, the system crashes with a nil pointer exception.

# How the Problems Are Solved

Replace this example text with a concise list of changes that this PR introduces.
For example:
- Validates if property XY is given and throws an error if not

# Additional Changes

Replace this example text with a concise list of additional changes that this PR introduces, that are not directly solving the initial problem but are related.
For example:
- The docs explicitly describe that the property XY is mandatory
- Adds missing translations for validations.

# Additional Context

Replace this example with links to related issues, discussions, discord threads, or other sources with more context.
Use the Closing #issue syntax for issues that are resolved with this PR.
- Closes #xxx
- Discussion #xxx
- Follow-up for PR #xxx
- https://discord.com/channels/xxx/xxx

2024-12-18 09:31 UTC, livio-a requested changes
can you please document the flow analog to https://zitadel.com/docs/guides/integrate/login-ui/oidc-standard
or create a follow up issue for it

2024-12-18 09:36 UTC, stebenz commented on proto/zitadel/settings/v2/login_settings.proto
> +  bool is_linking_allowed = 4;
Oh I think that accidentally went in as I was working on the other PR. Removed.

2024-12-18 09:37 UTC, stebenz commented on proto/zitadel/saml/v2/saml_service.proto
> +      description: "Callback URL where the user should be redirected, using a \"302 FOUND\" status. Contains details for the application to obtain the tokens on success, or error details on failure.
Tried to hold it as much as possible like OIDC, but yes your right, will rename and relable it SAML specific.

2024-12-18 09:45 UTC, stebenz commented on internal/repository/samlsession/saml_session.go
> +	Audience          []string                    `json:"audience"`
There is an audience in the response, currently only limited to the SP itself, but yes we have one.

2024-12-18 09:46 UTC, stebenz commented on internal/repository/samlsession/saml_session.go
> +	Actor    *domain.TokenActor `json:"actor,omitempty"`
Not used, missed to remove.

2024-12-18 09:48 UTC, stebenz commented on internal/repository/samlrequest/saml_request.go
> +	ApplicationID string `json:"application_id,omitempty"`
ApplicationID is the application itself, as the entityID could theoratically change, and the entityID is more or less only used to get the applicationID.
We could have implemented it to set the applicationID == entityID, so we would have no unique contraints problems, but that was a decision we took a long time ago.

2024-12-18 09:48 UTC, stebenz commented on internal/repository/samlrequest/saml_request.go
> +	IssuerName    string `json:"issuer_name,omitempty"`
Only included it as it is included in OIDC

2024-12-18 09:49 UTC, stebenz commented on internal/repository/samlrequest/saml_request.go
> +	Binding       string `json:"binding,omitempty"`
The binding in itself is a string in the request, and handled there, that's why I did it as a string here. We could parse it if necessary.

2024-12-18 09:54 UTC, stebenz commented on proto/zitadel/saml/v2/saml_service.proto
> +  string body = 2;
True, yes should always be the response in failure and success.

2024-12-18 09:57 UTC, stebenz commented on proto/zitadel/saml/v2/saml_service.proto
> +    PostResponse post = 4;
Structured it this way as you always should have an ACS URL, and you either have a URL with all the information or you have the URL and a post body.
IMO both options would be valid, can't really decide on what feels better.

2024-12-18 09:59 UTC, stebenz commented on internal/api/saml/auth_request_converter_v2.go
> +	return a.UserID
Good point, I think that's something unnecessary, but included in the interface from zitadel/saml, would need to remove it there as well.
https://github.com/zitadel/saml/blob/95c785b0bc2fec76c2901bbded1e685d5a6804fb/pkg/provider/models/models.go#L7

2024-12-18 10:00 UTC, stebenz commented on internal/api/saml/auth_request_converter_v2.go
> +	return a.IssuerName
Same here 
https://github.com/zitadel/saml/blob/95c785b0bc2fec76c2901bbded1e685d5a6804fb/pkg/provider/models/models.go#L13

2024-12-18 10:00 UTC, stebenz commented on internal/api/saml/auth_request_converter_v2.go
> +	return ""
Same here https://github.com/zitadel/saml/blob/95c785b0bc2fec76c2901bbded1e685d5a6804fb/pkg/provider/models/models.go#L11

2024-12-18 10:01 UTC, stebenz commented on internal/api/saml/auth_request_converter_v2.go
> +	return ""
Same here
https://github.com/zitadel/saml/blob/95c785b0bc2fec76c2901bbded1e685d5a6804fb/pkg/provider/models/models.go#L16

2024-12-18 10:01 UTC, stebenz commented on internal/command/saml_session.go
> +	Audience          []string
Yes, entityID is used as the audience currently.

2024-12-18 10:04 UTC, stebenz commented on internal/domain/saml_error_reason.go
> +	return SAMLErrorReasonUnspecified
Totally overlooked that, was a inbetween solution as I had to move over the relevant errors from zitadel/saml.

2024-12-18 12:50 UTC, stebenz commented on proto/zitadel/saml/v2/saml_service.proto
> +  rpc CreateCallback (CreateCallbackRequest) returns (CreateCallbackResponse) {
Originally it was to keep it consistent, but if you but it that way in my opinion we should name it something entirely  different.
Maybe just CreateResponse? In artifact binding and other binding you always have a Response message, which contains either the artifact response or the assertion.

2024-12-18 12:51 UTC, stebenz commented on proto/zitadel/saml/v2/saml_service.proto
> +  rpc GetAuthRequest (GetSAMLRequestRequest) returns (GetSAMLRequestResponse) {
Done

2024-12-18 13:13 UTC, stebenz commented on internal/api/saml/auth_request.go
> +		return fmt.Sprintf("%s?%s", authReq.GetAccessConsumerServiceURL(), provider.BuildRedirectQuery(string(respData), resp.RelayState, resp.SigAlg, resp.Signature)), "", nil
Not quite sure here, if I recall correctly there could be SAML entities using query params for resolving the enitityID, should I at least clear the specific SAML parameters?

2024-12-18 13:38 UTC, stebenz commented on internal/command/saml_session_model.go
> +	wm.SAMLResponseCreation = e.CreationDate().Add(e.Lifetime)
As mentioned in our conversion, left out for now as it is mainly used in OIDC impersonation.

2024-12-18 14:59 UTC, stebenz commented on internal/api/saml/auth_request.go
> +	return "", "", nil
moved it to a separate function

2024-12-19 09:30 UTC, livio-a requested changes

2024-12-19 10:51 UTC, livio-a approved these changes

2024-12-19 10:55 UTC, stebenz commented
Issue for documentation added https://github.com/zitadel/zitadel/issues/9088

2024-12-19 11:11 UTC, merged