fix: set correct owner on project grants
zitadel/zitadel pull request #9089
Opened 2024-12-19 11:00 UTC by adlerhurst

# Which Problems Are Solved

Replace this example text with a concise list of problems that this PR solves.
For example:
- If the property XY is not given, the system crashes with a nil pointer exception.

# How the Problems Are Solved

Replace this example text with a concise list of changes that this PR introduces.
For example:
- Validates if property XY is given and throws an error if not

# Additional Changes

Replace this example text with a concise list of additional changes that this PR introduces, that are not directly solving the initial problem but are related.
For example:
- The docs explicitly describe that the property XY is mandatory
- Adds missing translations for validations.

# Additional Context

Replace this example with links to related issues, discussions, discord threads, or other sources with more context.
Use the Closing #issue syntax for issues that are resolved with this PR.
- Closes #xxx
- Discussion #xxx
- Follow-up for PR #xxx
- https://discord.com/channels/xxx/xxx

2025-01-07 16:16 UTC, livio-a commented
as discussed: we want to create a tech advisory. for cloud customers, we'll inform corresponding admins and link them to the advisory

2025-01-14 07:04 UTC, livio-a requested changes

2025-01-15 09:24 UTC, adlerhurst commented on docs/docs/support/advisory/a10014.md
> +Version: v2.66.5
added versions

2025-01-15 10:22 UTC, livio-a approved these changes

2025-01-15 10:22 UTC, merged