fix: restructure resend email code to send email code
zitadel/zitadel pull request #9099
Opened 2024-12-20 15:52 UTC by stebenz

# Which Problems Are Solved

There is currently no endpoint to send an email code for verification of the email if you don't change the email itself.

# How the Problems Are Solved

Endpoint HasEmailCode to get the information that an email code is existing, used by the new login.
Endpoint SendEmailCode, if no code is existing to replace ResendEmailCode as there is a check that a code has to be there, before it can be resend.

# Additional Changes

None

# Additional Context

Closes #9096

2024-12-24 11:07 UTC, adlerhurst requested changes
code looks good, only 4 comments which are wrong

2024-12-24 11:07 UTC, adlerhurst commented on internal/command/user_v2_email_test.go
> +			// successful cases are tested in TestCommands_resendUserEmailCodeWithGenerator
I cannot find the tests mentioned.
```suggestion
			// successful cases are tested in TestCommands_sendUserEmailCodeWithGenerator
```

2024-12-24 11:07 UTC, adlerhurst commented on internal/command/user_v2_email_test.go
> +			// successful cases are tested in TestCommands_resendUserEmailCodeWithGenerator
I cannot find the tests mentioned.
```suggestion
			// successful cases are tested in TestCommands_sendUserEmailCodeWithGenerator
```

2024-12-24 11:07 UTC, adlerhurst commented on internal/command/user_v2_email_test.go
> +			// successful cases are tested in TestCommands_changeUserEmailWithGenerator
I cannot find the tests mentioned.
```suggestion
			// successful cases are tested in TestCommands_sendUserEmailCodeWithGenerator
```

2024-12-24 11:07 UTC, adlerhurst commented on internal/command/user_v2_email_test.go
> +			// successful cases are tested in TestCommands_changeUserEmailWithGenerator
I think same applies to line [720](https://gitkraken.dev/link/dnNjb2RlOi8vZWFtb2Rpby5naXRsZW5zL2xpbmsvci82NjFiY2ZiZGVjZGNjNzliNGEyOGU1YmIyNTJhNTgwZGU0YmE1MzJjL2YvaW50ZXJuYWwvY29tbWFuZC91c2VyX3YyX2VtYWlsX3Rlc3QuZ28%2FdXJsPWdpdCU0MGdpdGh1Yi5jb20lM0F6aXRhZGVsJTJGeml0YWRlbC5naXQmbGluZXM9NzIw?origin=gitlens)

2024-12-24 11:09 UTC, adlerhurst commented
please also have a look at the copilot review

2024-12-27 09:12 UTC, stebenz commented
> please also have a look at the copilot review

Corrected the wrongly mentioned functions in the comments.
Had a look at the copilot review, can change the text, but as it is a oneOf and 'nil' is also checked, default will never happen through an API call. Should we leave this be for now or introduce unit testing for all oneOf mappings in the API?

2024-12-27 10:22 UTC, adlerhurst approved these changes

2024-12-27 15:34 UTC, merged