fix: add search queries to ListSessions and remodel integration tests
zitadel/zitadel pull request #9110
Opened 2024-12-27 16:05 UTC by stebenz

# Which Problems Are Solved

ListSessions only works to list the sessions that you are the creator of.

# How the Problems Are Solved

Add SearchQuery's to the ListSessions endpoint, so that you can also search for sessions without you as a creator and which belong to your UserAgent.

# Additional Changes

Remodel integration tests, to separate the Create and Get of sessions correctly.

# Additional Context

Closes #8301

2025-01-10 07:57 UTC, livio-a requested changes
Can you please also update the PR description.
IMO it currently states the technical problem and change, but not the use case.

2025-01-10 07:57 UTC, livio-a commented on internal/api/grpc/session/v2/integration_test/query_test.go
> +	}
please add tests for the user agent query

2025-01-10 08:15 UTC, stebenz commented on internal/query/session.go
> +}
So you mean org and userID for the permission check?
I tried to keep it persistent with https://github.com/zitadel/zitadel/blob/af09e51b1eeddefa524f94424c431f4ac9b016d5/internal/query/auth_request.go#L39 do we have to change this permission check as well?

2025-01-10 14:28 UTC, stebenz commented on internal/query/session.go
> +}
permission check changed and added unit test

2025-01-10 14:28 UTC, stebenz commented on internal/query/session.go
> +		if err := sessionCheckPermission(ctx, session.ResourceOwner, session.Creator, session.UserFactor, permissionCheck); err != nil {
same as above

2025-01-10 14:29 UTC, stebenz commented on internal/api/grpc/session/v2/query.go
> +		return query.NewSessionUserAgentFingerprintIDSearchQuery(authz.GetCtxData(ctx).AgentID)
added error if user agent query is done with empty user agent

2025-01-10 14:29 UTC, stebenz commented on internal/api/grpc/session/v2/integration_test/query_test.go
> +	}
tests added

2025-01-14 06:46 UTC, livio-a requested changes

2025-01-14 06:46 UTC, livio-a commented on proto/zitadel/session/v2/session.proto
> +  // ID of the user used to create the session, if empty the id of the calling user is used as creator.
```suggestion
  // ID of the user who created the session. If empty, the calling user's ID is used.
```

2025-01-14 06:46 UTC, livio-a commented on proto/zitadel/session/v2/session.proto
> +  optional string id = 1 [
I've looked at this again and would make it clearer incl. naming it fingerprint_id to match the name in the `UserAgent` message:
```suggestion
  // Finger print id of the user agent used for the session.
  // Set an empty fingerprint_id to use the user agent from the call.
  // If the user agent is not available from the current token, an error will be returned.
  optional string fingerprint_id = 1 [
```

2025-01-14 06:46 UTC, livio-a commented on proto/zitadel/session/v2/session.proto
> +    UserAgentQuery useragent_query = 5;
```suggestion
    UserAgentQuery user_agent_query = 5;
```

2025-01-14 06:46 UTC, livio-a commented on internal/api/grpc/session/v2/query.go
> +		if agentID := authz.GetCtxData(ctx).AgentID; agentID != "" {
Shouldn't we also check that the useragent query / GetID is not nil / just empty?
Otherwise it would introduce a breaking change if we add more possibilities to the user agent query (e.g. allow filtering by IP)

2025-01-14 08:08 UTC, stebenz commented on internal/api/grpc/session/v2/query.go
> +		if agentID := authz.GetCtxData(ctx).AgentID; agentID != "" {
Makes sense, thought of that as well, but was put off as it could cause confusion. Will change it.

2025-01-14 09:22 UTC, livio-a approved these changes

2025-01-14 13:15 UTC, merged